meltano/sdk

- samples/sample_tap_bigquery/__init__.py
- singer_sdk/streams/sql.py
As discussed in Slack: https://meltano.slack.com/archives/C01PKLU5D1R/p1653575557167359
There are situations when SQLAlchemy inspection behavior should be tweaked. It would be nice to tweak only relevant parts without large copy-paste.
I propose a refactor of `SQLConnector.discover_catalog_entries` and `sample_tap_bigquery` to illustrate why it's needed.
Closes #682
> SQL connector modular discover

- CONTRIBUTING.md
- docs/implementation/catalog_metadata.md
Removes gitlab references.
I did a full text search in the repo for all occurrences of 'gitlab' in the full contents. Ignored these:
- changlog references (pointers to closed MRs and Issues)
- tap-gitlab references
- other pointers to historic gitlab issues which were not migrated and which still offer explanatory value
> docs: update gitlab refs to github ones

- .github/dependabot.yml
`increase-if-necessary` is not supported for pip dependencies. I think we can rely on the default behavior for libraries:
> When Dependabot edits a manifest file to update a version, it uses the following overall strategies:
> 
> - For apps, the version requirements are increased, for example: npm, pip and Composer.
> - For libraries, the range of versions is widened, for example: Bundler and Cargo.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy
> chore: Remove unsupported versioning-strategy value

- singer_sdk/helpers/_state.py
- singer_sdk/streams/core.py
This change adds a new boolean property to core: check_sorted
By default, `check_sorted = True`, which is the behavior currently when `is_sorted = True`.
However, there are API's that are sorted, but not by `replication_key`.
This change allows for an API that is truly ordered, but where the `replication_key` is not an incremental one.
Closes #729
> feat(taps): Allow sort checking to be disabled

- CHANGELOG.md
- singer_sdk/helpers/_state.py
> fix: Check if RK is sortable before comparing

- .gitlab-ci.yml
To save us a few minutes worth of GitLab CI
> ci: Drop test and lint jobs still running on GitLab CI

- .pre-commit-config.yaml
Closes #821 
I don't see a downside to this, maybe there's a reason this config setting was used?
> chore: Remove `python3.10` requirement from black pre-commit hook

- .github/workflows/dependency-review.yml
```
Error: This run was triggered by the "push" event, which is unsupported. Please ensure you are using the "pull_request" event for this workflow.
```
> ci: Update workflow because GitHub dependency review can only run in PRs

- .github/workflows/dependency-review.yml
Closes #841
This will make this workflow work for PRs from external contributors, since it'll run in the context of the base, and therefore have access to our secrets.
> ci: Use `pull_request_target` for dependency review workflow

- docs/code_samples.md
Found some extra whitespace that might as well be removed.
> docs: Cleanup whitespace in backoff code samples

- singer_sdk/streams/rest.py
> fix(taps): Update return type for `backoff_max_tries` to reflect it accepts a callable that returns an integer

- singer_sdk/streams/rest.py
I was running into an error similar to [this on Github](https://stackoverflow.com/questions/52051989/requests-exceptions-connectionerror-connection-aborted-connectionreseterro). So I decided to address it by adding it to the list of back off exceptions.
This fixed the issue for me.
> feat: add `ConnectionError` to list of backoff exceptions for auto-retry

- .github/workflows/test.yml
Cancels running jobs when new commits are pushed.
Copied from @WillDaSilva's work on `meltano/meltano`.
> ci: Limit test job concurrency

- singer_sdk/helpers/_schema.py
- singer_sdk/helpers/_singer.py
- singer_sdk/streams/core.py
- singer_sdk/streams/sql.py
- tests/core/test_catalog_selection.py
- tests/core/test_schema.py
Closes [#901](https://github.com/meltano/sdk/issues/901)
The use of the Schema class from a dependency was limiting schemas to only include certain declared json schema fields, since it would remove properties if they were not whitelisted.  Since this is from a dependency, we can't simply expand the whitelist so instead we override the class and expand the list there. An alternative implementation would be to simply replace the class outright (no inheritance) - this could break existing taps that pass a Schema to Stream.init though.
It helps with but does not close [#332](https://github.com/meltano/sdk/issues/332), since 332 is asking for helpers, which this does not add - it makes it possible to add them though.
I think there are lots more improvements that could be made to SchemaPlus in …
> fix: Allow Singer schemas to include the `required` and `enum` fields

- .github/workflows/version_bump.yml
- poetry.lock
- pyproject.toml
To customize how Commitizen performs our version bump, Meltano and the SDK will now use https://github.com/meltano/commitizen-version-bump. It will be installed and used by commitizen-action in the version_bump GitHub workflow.
All of the customizations used by the SDK should continue to work unchanged: https://github.com/meltano/commitizen-version-bump/commit/d049f8eb96d9c2c0718b669c04d491d6bbea0124
Relates to https://github.com/meltano/gitops/issues/4
> ci: Use `meltano/commitizen-version-bump`

- .github/workflows/pr-preview-links.yml
Add docs preview links to PR description. Will be available after this lands on `main`.
> docs: Add docs preview links to PR description

- docs/classes/singer_sdk.exceptions.RecordsWithoutSchemaException.rst
- docs/reference.rst
- singer_sdk/exceptions.py
- singer_sdk/target_base.py
> fix: Fix typo RecordsWitoutSchemaException -> RecordsWithoutSchemaException

- docs/classes/singer_sdk.exceptions.RecordsWitoutSchemaException.rst
----
:books: Documentation preview :books:: https://meltano-sdk--947.org.readthedocs.build/en/947/
> docs: Remove stale autodoc page for RecordsWitoutSchemaException

- samples/sample_tap_gitlab/schemas/epic_issues.json
This error (a missing PK) was uncovered after https://github.com/meltano/sdk/pull/829/ landed on `main`.
Schema generated with https://github.com/edgarrmondragon/jsonschema-infer-tool/ from the example in the GitLab API docs.
----
:books: Documentation preview :books:: https://meltano-sdk--944.org.readthedocs.build/en/944/
> ci: Fix missing PK in GitLab external tests

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/README.md
- cookiecutter/target-template/{{cookiecutter.target_id}}/README.md
Resolves #969
----
:books: Documentation preview :books:: https://meltano-sdk--970.org.readthedocs.build/en/970/
> docs: Move cookiecutter TODOs into markdown comments

- .github/semantic.yml
`CONTRIBUTING.md` was moved to the docs a while ago.
----
:books: Documentation preview :books:: https://meltano-sdk--991.org.readthedocs.build/en/991/
> ci: Change `targetUrl` of semantic PR title check to point to SDK docs

- .github/ISSUE_TEMPLATE/bug.yml
- CHANGELOG.md
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
- docs/conf.py
- pyproject.toml
This reverts commit 308847fe177d105dffa10ae623f199b1097d03f0.
----
:books: Documentation preview :books:: https://meltano-sdk--1004.org.readthedocs.build/en/1004/
> chore: Revert release v0.12.0

- singer_sdk/streams/sql.py
----
:books: Documentation preview :books:: https://meltano-sdk--1001.org.readthedocs.build/en/1001/
> fix: Use column name in `allow_column_alter` error message

- README.md
as discussed in https://github.com/meltano/internal-marketing/issues/684.
----
:books: Documentation preview :books:: https://meltano-sdk--1006.org.readthedocs.build/en/1006/
> docs: Add links to Meltano install/tut

- docs/stream_maps.md
Confusing when text refers to one property, and the code example later refers to another (correct one).
----
:books: Documentation preview :books:: https://meltano-sdk--1020.org.readthedocs.build/en/1020/
> docs: Fixed typo in `docs/stream_maps.md`

- singer_sdk/streams/sql.py
Closes #974 
- #974 
----
:books: Documentation preview :books:: https://meltano-sdk--1032.org.readthedocs.build/en/1032/
> feat: Support stream property selection push-down in SQL streams

- docs/CONTRIBUTING.md
- pyproject.toml
- singer_sdk/helpers/_batch.py
- tests/conftest.py
- tests/core/test_batch.py
A proposed solutions to issue #1042.  This fix for `StorageTarget.split()` adds detection of Windows and the presence of `\` in url.  If it detects both Windows and `\` it splits the url and returns the results. The split logic is a rework of the code from [fs.path.split ](https://docs.pyfilesystem.org/en/latest/_modules/fs/path.html#split). 
Closes #1042 
----
:books: Documentation preview :books:: https://meltano-sdk--1043.org.readthedocs.build/en/1043/
> fix: Batch storage `split_url` to work with Windows paths

- .github/ISSUE_TEMPLATE/docs.yml
Maybe missing or unclear documentation qualifies as a _bug_, but it's probably worth having a dedicated template for doc requests.
----
:books: Documentation preview :books:: https://meltano-sdk--1063.org.readthedocs.build/en/1063/
> chore: Add issue template for documentation

- singer_sdk/pagination.py
----
:books: Documentation preview :books:: https://meltano-sdk--1074.org.readthedocs.build/en/1074/
> docs: Document an example implementation and usage of `BaseHATEOASPaginator`

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/meltano.yml
- cookiecutter/target-template/{{cookiecutter.target_id}}/meltano.yml
Closes https://github.com/meltano/sdk/issues/1092
Related to slack thread https://meltano.slack.com/archives/C01TCRBBJD7/p1666232552939149
----
:books: Documentation preview :books:: https://meltano-sdk--1093.org.readthedocs.build/en/1093/
> fix(templates): add environment support to the cookie cutter for `meltano.yml`

- singer_sdk/streams/sql.py
Closes #1110 
- #1110 
----
:books: Documentation preview :books:: https://meltano-sdk--1111.org.readthedocs.build/en/1111/
> fix: push _MAX_RECORDS_LIMIT down into SQL

- docs/batch.md
cc @edgarrmondragon, @kgpayne, @tayloramurphy 
----
:books: Documentation preview :books:: https://meltano-sdk--1118.org.readthedocs.build/en/1118/
> docs: document `BATCH` limitations

- .github/workflows/test.yml
- noxfile.py
- poetry.lock
- pyproject.toml
- tests/core/test_target_parquet_init.py
This just adds a few lines to run CI tests on the recently released python 3.11.
Substantial speedups are expected, and as the taps and targets are run inside their own virtual envs, it should be pretty easy to upgrade them even if the main app is running on an earlier version of python.
----
:books: Documentation preview :books:: https://meltano-sdk--1115.org.readthedocs.build/en/1115/
> chore: Add support for python 3.11

- singer_sdk/tap_base.py
- tests/core/test_countries_sync.py
Refer to this [slack thread](https://meltano.slack.com/archives/C01PKLU5D1R/p1668012985498759).
This PR adds a call to issue a final (valid) state message at the end of each stream sync.
In some cases, messages sent by the tap were invalid. For instance, if `state_partitioning_keys` is overridden in a stream, the stream would never issue a valid state message, making incremental syncs impossible.
Here is an example of the last message issued by `tap-github` when running on the `issue_comments` stream (which has `state_partitioning_keys` overridden). `progress_markers` should not be present in the output, and `replication_key_value` should have been promoted one level up.
```json
{"type": "STATE", "value": {"bookmarks": {
"tempStream": {},
"repositories": {"partitions": [{"context": …
```
> fix: Write a valid final state message at the end of each stream sync

- singer_sdk/connectors/sql.py
Attempt to fix `table_exists()` to use the parsed `full_table_name` parts table and schema instead of a combined multipart name.
Fixes #1167  
----
:books: Documentation preview :books:: https://meltano-sdk--1168.org.readthedocs.build/en/1168/
> fix: `SQLConnector.table_exists()` to use separate `table_name` and `schema_name` instead of fully qualified name

- docs/stream_maps.md
- singer_sdk/mapper.py
- tests/core/test_mapper.py
Closes #986
This adds the datetime module to the simpleeval environment, similarly to how an md5 function was added. This enables datetime handling/processing in streammaps.
----
:books: Documentation preview :books:: https://meltano-sdk--1175.org.readthedocs.build/en/1175/
> feat(mappers): Add `datetime` functions to simpleeval env in stream maps

- cookiecutter/target-template/{{cookiecutter.target_id}}/{{cookiecutter.library_name}}/sinks.py
It appears, with sdk v0.13.1, the location of the `SQLConnector` class was moved from `singer_sdk.sinks` to `singer_sdk.connectors`. This is intended to reflect this change in the cookiecutter sql-target template.
----
:books: Documentation preview :books:: https://meltano-sdk--1182.org.readthedocs.build/en/1182/
> fix(templates): Update `SQLConnector` import for SQL target cookiecutter

- singer_sdk/streams/rest.py
Closes #1236
----
:books: Documentation preview :books:: https://meltano-sdk--1237.org.readthedocs.build/en/1237/
> feat(taps): Catch and retry `ConnectionResetError` exceptions in HTTP taps

- docs/implementation/logging.md
- poetry.lock
- singer_sdk/default_logging.yml
- singer_sdk/plugin_base.py
Closes https://github.com/meltano/sdk/issues/1232
----
:books: Documentation preview :books:: https://meltano-sdk--1233.org.readthedocs.build/en/1233/
> fix: Add level and logger name to default log format

- docs/_templates/plugin_class.rst
- docs/classes/singer_sdk.InlineMapper.rst
- docs/classes/singer_sdk.SQLTap.rst
- docs/classes/singer_sdk.SQLTarget.rst
- docs/classes/singer_sdk.Tap.rst
- docs/classes/singer_sdk.Target.rst
- docs/reference.rst
- singer_sdk/plugin_base.py
Some attributes and methods, such as `Tap.print_version`, weren't documented because we exclude `PluginBase` from the docs (probably with good reason, since developers should seldom need to subclass it directly).
Now they're documented: https://meltano-sdk--1243.org.readthedocs.build/en/1243/classes/singer_sdk.Tap.html#singer_sdk.Tap.print_version
----
:books: Documentation preview :books:: https://meltano-sdk--1243.org.readthedocs.build/en/1243/
> docs: Document inherited `PluginBase` attributes and methods

- singer_sdk/metrics.py
- tests/core/test_metrics.py
Otherwise adding objects in a streams `context` that can't be JSON-serialized cause the tap to fail.
For example, pendulum objects in [tap-lastfm](https://github.com/rabidaudio/tap-lastfm/blob/606b4608355a37609e81be0827d2283f4cb94cd4/tap_lastfm/streams.py#L58-L63).
Closes https://github.com/meltano/sdk/issues/1239
> fix(taps): Ensure metric tags coming from stream context can be JSON-serialized

- singer_sdk/typing.py
- tests/snapshots/jsonschema/required_duplicates.json
- tests/snapshots/jsonschema/required_duplicates_additional_properties.json
- tests/snapshots/jsonschema/required_duplicates_no_additional_properties.json
Closes https://github.com/meltano/sdk/issues/1210
----
:books: Documentation preview :books:: https://meltano-sdk--1214.org.readthedocs.build/en/1214/
> fix: Avoid duplicate entries in `required` array of JSON schema helpers

- singer_sdk/target_base.py
Closes https://github.com/meltano/sdk/issues/1145
Example implementation https://github.com/MeltanoLabs/target-postgres/commit/41822b548ef99dcb5aa79ea140e872a6beb7892a
----
:books: Documentation preview :books:: https://meltano-sdk--1287.org.readthedocs.build/en/1287/
> fix: Targets to fail gracefully when schema message is missing the `properties` key

- docs/index.rst
----
:books: Documentation preview :books:: https://meltano-sdk--1293.org.readthedocs.build/en/1293/
> docs: Add links to EDK And Hub

- docs/code_samples.md
I was using [the code samples docs](https://sdk.meltano.com/en/latest/code_samples.html#dynamically-discovering-schema-for-a-stream) for remembering how to do dynamic schema discovery and noticed a few bugs that made a copy/paste not work:
- missing a colon in for loop
- the cookiecutter imports `from singer_sdk import typing as th` so all  the properties references needed to be prefixed with `th.` to work
----
:books: Documentation preview :books:: https://meltano-sdk--1306.org.readthedocs.build/en/1306/
> docs: Update code samples docs

- docs/CONTRIBUTING.md
- singer_sdk/plugin_base.py
Currently, we're looking for `cls.name.upper()`, with hyphens intact. Since hyphens are not allowed in shell variable names, this makes it impossible to set the loglevel for a single tap. This change makes this variable match other plugin specific variables by replacing hyphens with underscores.
Also, fix a formatting glitch in the contributing guide.
----
:books: Documentation preview :books:: https://meltano-sdk--1308.org.readthedocs.build/en/1308/
> fix(taps): Replace hyphens with underscores when generating expected env var name `<PLUGIN_NAME>_LOGLEVEL`

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/{% if cookiecutter.include_cicd_sample_template == 'GitHub' %}ci_workflow.yml{%endif%}
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/tox.ini
- cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
Closes https://github.com/meltano/sdk/issues/1223 and https://github.com/meltano/sdk/issues/1225
I ran into these same bugs when using the cookiecutter for https://github.com/pnadolny13/tap-cloudwatch and had to resolve them for my implementation. Heres what ended up working for me.
- github action install poetry dependencies before running tox
- bump black version
- migrate from legacy poetry dev dependencies to group.dev. I removed black then readded it and poetry did this automatically for me with a warning.
----
:books: Documentation preview :books:: https://meltano-sdk--1305.org.readthedocs.build/en/1305/
> fix(templates): Install dependencies in CI and bump dev dependencies

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
- docs/dev_guide.md
- poetry.lock
Per @edgarrmondragon's [suggestion](https://github.com/meltano/sdk/issues/1311#issuecomment-1402682760), the documentation has been updated to suggest it be installed using `pipx`
Closes #1311
----
:books: Documentation preview :books:: https://meltano-sdk--1345.org.readthedocs.build/en/1345/
> fix: Remove tox dependency from tap/target template

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
- poetry.lock
While addressing #1311, I noticed that the `flake8` dependency was somewhat old, so I am updating it now to try and stave off dependency conflicts later. 
----
:books: Documentation preview :books:: https://meltano-sdk--1346.org.readthedocs.build/en/1346/
> chore: Update `flake8` from `^3.9.2` to `^5.0.4` in templates

- docs/dev_guide.md
----
:books: Documentation preview :books:: https://meltano-sdk--1358.org.readthedocs.build/en/1358/
> docs: Fix typo in `if __name__ == ` example

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
See https://github.com/pycqa/isort/blob/main/CHANGELOG.md#5115-january-30-2023-hotfix
----
:books: Documentation preview :books:: https://meltano-sdk--1406.org.readthedocs.build/en/1406/
> fix(templates): Use a version of `isort` compatible with Python 3.8

- .github/workflows/version_bump.yml
Release notes: https://github.com/commitizen-tools/commitizen-action/releases/tag/0.16.3
----
:books: Documentation preview :books:: https://meltano-sdk--1408.org.readthedocs.build/en/1408/
> chore: Use `commitizen-action@0.16.3`

- e2e-tests/cookiecutters/test_cookiecutter.sh
Fixes #1444 
- in e2e test for cookiecutter, use local singer-sdk folder as dependency
- use sed to edit pyproject.toml in place: confirmed working with ubuntu + macos sed :)
----
:books: Documentation preview :books:: https://meltano-sdk--1445.org.readthedocs.build/en/1445/
> ci(templates): Use a local reference to the `singer-sdk` instead of PyPI distribution in E2E cookiecutter tests

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/{%if 'REST' == cookiecutter.stream_type %}client.py{%endif%}
Change config key for bearer auth for REST APIs so that it is consistent across files and works out of the box.
Closes #1452
----
:books: Documentation preview :books:: https://meltano-sdk--1454.org.readthedocs.build/en/1454/
> fix: Cookiecutter bearer auth config

- mypy.ini
- noxfile.py
- poetry.lock
- pyproject.toml
- singer_sdk/_singerlib/schema.py
- singer_sdk/plugin_base.py
- singer_sdk/typing.py
----
:books: Documentation preview :books:: https://meltano-sdk--1456.org.readthedocs.build/en/1456/
> chore: Do not ignore `jsonschema` in mypy checks

- .github/workflows/dependency-review.yml
----
:books: Documentation preview :books:: https://meltano-sdk--1468.org.readthedocs.build/en/1468/
> chore: Change upstream deps review action back to `actions/dependency-review-action`

- .flake8
- .pre-commit-config.yaml
- docs/CONTRIBUTING.md
- noxfile.py
- pyproject.toml
- singer_sdk/helpers/_flattening.py
- singer_sdk/helpers/_state.py
- singer_sdk/typing.py
- tests/core/test_batch.py
- tests/core/test_connector_sql.py
- tests/core/test_mapper.py
- tests/core/test_metrics.py
- tests/core/test_plugin_config.py
- tests/core/test_schema.py
- tests/core/test_typing.py
- tests/external/conftest.py
- tests/external/test_tap_gitlab.py
- tests/samples/test_tap_sqlite.py
- tests/samples/test_target_csv.py
- tests/samples/test_target_sqlite.py
This PR introduces a few Ruff checks without being too aggressive. We can add more rules progressively.
In the meantime:
- Auto-fixed unused imports (F401)
- Fixed some unused variables and redefined test functions
- Fixed docstring conventions in `singer_sdk/helpers/_state.py`
- Fixed some imports and removed `isort` from pre-commit
Can't get rid of flake8 entirely yet due to https://github.com/charliermarsh/ruff/issues/458
Closes https://github.com/meltano/sdk/issues/1242
----
:books: Documentation preview :books:: https://meltano-sdk--1462.org.readthedocs.build/en/1462/
> ci: Use Ruff to lint project

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/{% if cookiecutter.include_cicd_sample_template == 'GitHub' %}ci_workflow.yml{%endif%}
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/tox.ini
Plus some related cleanup. Poetry still needs to be installed before running `pipx run tox ...` because tox is configured to use poetry from the external environment, rather than installing it into the tox venv.
Supersedes:
- https://github.com/meltano/sdk/pull/1476
Closes #1481
----
:books: Documentation preview :books:: https://meltano-sdk--1482.org.readthedocs.build/en/1482/
> fix: Use pipx to run tox in CI template

- docs/code_samples.md
- singer_sdk/streams/rest.py
Closes #1477 
----
:books: Documentation preview :books:: https://meltano-sdk--1480.org.readthedocs.build/en/1480/
> feat: Added `RESTStream.backoff_jitter` to support custom backoff jitter generators

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
Just to be more explicit, we could remove `pytest` later since it's now an extra transitive dependency.
cc @kgpayne 
----
:books: Documentation preview :books:: https://meltano-sdk--1483.org.readthedocs.build/en/1483/
> chore(templates): Include singer-sdk[testing] in templates dev dependencies

- singer_sdk/streams/rest.py
Recieved a few of these errors in production with long running jobs, retries will now save the day!
----
:books: Documentation preview :books:: https://meltano-sdk--1478.org.readthedocs.build/en/1478/
> feat: Retry some streaming and decoding request errors

- noxfile.py
- pyproject.toml
- samples/sample_tap_sqlite/__init__.py
- samples/sample_target_sqlite/__init__.py
- singer_sdk/connectors/sql.py
- singer_sdk/sinks/sql.py
- singer_sdk/streams/sql.py
- tests/core/test_connector_sql.py
- tests/samples/conftest.py
- tests/samples/test_target_sqlite.py
This doesn't yet add support for SQLAlchemy 2.0 (https://github.com/meltano/sdk/pull/1484/), since downstream SQL taps and targets may need to either pin the SDK or set an upper limit for SQLAlchemy.
https://docs.sqlalchemy.org/en/20/changelog/migration_20.html
----
:books: Documentation preview :books:: https://meltano-sdk--1487.org.readthedocs.build/en/1487/
> fix: Address SQLAlchemy 2.0 deprecation warnings

- noxfile.py
- poetry.lock
- pyproject.toml
- tests/samples/test_target_parquet.py
Closes #1465 
----
:books: Documentation preview :books:: https://meltano-sdk--1467.org.readthedocs.build/en/1467/
> fix(deps): Remove `debugging` and `samples` extras (they were never really available to users)

- pyproject.toml
- samples/sample_tap_gitlab/gitlab_graphql_streams.py
- singer_sdk/_singerlib/messages.py
- singer_sdk/helpers/_state.py
- singer_sdk/helpers/capabilities.py
- singer_sdk/sinks/sql.py
- singer_sdk/streams/rest.py
- singer_sdk/tap_base.py
- singer_sdk/typing.py
- tests/core/test_jsonschema_helpers.py
Motivation for [`flake8-implicit-str-concat`](https://pypi.org/project/flake8-implicit-str-concat/):
> This is a plugin for the Python code-checking tool Flake8 to encourage correct string literal concatenation.
>
> It looks for style problems like implicitly concatenated string literals on the same line (which can be introduced by the code-formatting tool Black), or unnecessary plus operators for explicit string literal concatenation.
----
:books: Documentation preview :books:: https://meltano-sdk--1499.org.readthedocs.build/en/1499/
> chore: Enable `ISC` Ruff checks

- pyproject.toml
<blockquote>
<h2>Rationale</h2>
<p>Implicit namespace packages are directories of Python files without an <code>__init__.py</code>.
They’re valid and importable, but they break <em>many</em> tools, such as:</p>
<ul>
<li><p><a href="https://bugs.python.org/issue23882" rel="nofollow">unittest test discovery</a> (and by extension, Django’s test runner)</p></li>
<li><p><a href="https://github.com/nedbat/coveragepy/issues/1024" rel="nofollow">Coverage.py</a></p></li>
<li><p>Mypy without its <a href="https://mypy.readthedocs.io/en/latest/command_line.html#import-discovery" rel="nofollow">–namespace-packages option</a></p></li>
<li><p><a href="https://github.com/pytest-dev/pytest/issues/5147" rel="nofollow">pytest</a></p></li>
</ul>
</blockquote>
https://pypi.org/project/flake8-no-pep420/
---- …
> chore: Enable `INP` Ruff checks

- pyproject.toml
- singer_sdk/plugin_base.py
- singer_sdk/tap_base.py
Usage of `print`
----
:books: Documentation preview :books:: https://meltano-sdk--1508.org.readthedocs.build/en/1508/
> chore: Enable `T20` Ruff checks

- pyproject.toml
- samples/sample_tap_hostile/hostile_streams.py
- singer_sdk/_singerlib/catalog.py
- singer_sdk/configuration/_dict_config.py
- singer_sdk/connectors/sql.py
- singer_sdk/helpers/_flattening.py
- singer_sdk/helpers/_state.py
- singer_sdk/helpers/_typing.py
- singer_sdk/plugin_base.py
- singer_sdk/sinks/core.py
- singer_sdk/sinks/sql.py
- singer_sdk/streams/core.py
- singer_sdk/streams/rest.py
- singer_sdk/tap_base.py
- singer_sdk/testing/runners.py
- tests/core/configuration/test_dict_config.py
- tests/core/test_connector_sql.py
----
:books: Documentation preview :books:: https://meltano-sdk--1509.org.readthedocs.build/en/1509/
> chore: Enable `SIM` Ruff checks

- docs/guides/pagination-classes.md
* Get rid of confusing type annotations
* Use the right classes
----
:books: Documentation preview :books:: https://meltano-sdk--1518.org.readthedocs.build/en/1518/
> docs: Fix HATEOAS pagination example

- singer_sdk/helpers/_typing.py
- tests/core/test_jsonschema_helpers.py
Uncovered in https://github.com/MeltanoLabs/tap-dbt/pull/119
----
:books: Documentation preview :books:: https://meltano-sdk--1526.org.readthedocs.build/en/1526/
> fix: Handle missing `type` value when checking JSON schema types

- docs/implementation/logging.md
- singer_sdk/metrics.py
- tests/core/test_metrics.py
According to the [Singer Spec](https://github.com/singer-io/getting-started/blob/master/docs/SYNC_MODE.md#metric-messages), the correct field name is `type` and not `metric_type`.
----
:books: Documentation preview :books:: https://meltano-sdk--1574.org.readthedocs.build/en/1574/
> fix: Conform metric field `type` to Singer spec

- singer_sdk/typing.py
- tests/core/test_jsonschema_helpers.py
Docs updates:
- [`PropertiesList` usage example](https://meltano-sdk--1603.org.readthedocs.build/en/1603/typing.html#usage-example)
- [`StringType` with and without initialization](https://meltano-sdk--1603.org.readthedocs.build/en/1603/classes/typing/singer_sdk.typing.StringType.html)
----
:books: Documentation preview :books:: https://meltano-sdk--1603.org.readthedocs.build/en/1603/
> feat: Allow `allowed_values` and `examples` in any JSON schema type constructor

- .pre-commit-config.yaml
Dependabot is still on Poetry 1.3 and our pre-commit check is on 1.4.0 so this is causing local pre-commit checks to fail and update the `poetry.lock` after a Dependabot PR was merged.
----
:books: Documentation preview :books:: https://meltano-sdk--1647.org.readthedocs.build/en/1647/
> chore: Remove `poetry-lock` pre-commit check

- singer_sdk/authenticators.py
- singer_sdk/streams/core.py
- singer_sdk/streams/rest.py
- singer_sdk/streams/sql.py
----
:books: Documentation preview :books:: https://meltano-sdk--1664.org.readthedocs.build/en/1664/
> chore: Leverage typing-only imports to avoid importing the base class

- .readthedocs.yml
See https://github.com/readthedocs/readthedocs.org/issues/10290 for details on the fix.
Affected docs builds:
* https://github.com/meltano/sdk/pull/1670
* https://github.com/meltano/sdk/pull/1669
----
:books: Documentation preview :books:: https://meltano-sdk--1673.org.readthedocs.build/en/1673/
> docs: Fix docs build by specifying OS in RTD config file

- docs/dev_guide.md
Theres already a VS section in the docs for debugging but I've seen a couple people in slack get hung up when using PyCharm. I found also found this article https://medium.com/@danthelion/meltano-development-how-to-debug-singer-taps-in-pycharm-18c481a55c47.
----
:books: Documentation preview :books:: https://meltano-sdk--1685.org.readthedocs.build/en/1685/
> docs: Add PyCharm debugging tips to docs

- singer_sdk/sinks/core.py
Fixes https://github.com/meltano/sdk/issues/1702
----
:books: Documentation preview :books:: https://meltano-sdk--1703.org.readthedocs.build/en/1703/
> docs: Fix broken docs link for `record_metadata` page

- cookiecutter/tap-template/cookiecutter.json
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{%if 'Apache-2.0' == cookiecutter.license %}LICENSE{%endif%}
- cookiecutter/target-template/cookiecutter.json
- cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
- cookiecutter/target-template/{{cookiecutter.target_id}}/{%if 'Apache-2.0' == cookiecutter.license %}LICENSE{%endif%}
- e2e-tests/cookiecutters/tap-graphql-jwt.json
- e2e-tests/cookiecutters/tap-other-custom.json
- e2e-tests/cookiecutters/tap-rest-api_key-github.json
- e2e-tests/cookiecutters/tap-rest-basic_auth.json
- e2e-tests/cookiecutters/tap-rest-bearer_token.json
- e2e-tests/cookiecutters/tap-rest-custom.json
- e2e-tests/cookiecutters/tap-rest-jwt.json
- e2e-tests/cookiecutters/tap-rest-oauth2.json
- e2e-tests/cookiecutters/tap-sql-custom.json
- e2e-tests/cookiecutters/target-per_record.json
- e2e-tests/cookiecutters/target-sql.json
- pyproject.toml
----
:books: Documentation preview :books:: https://meltano-sdk--1709.org.readthedocs.build/en/1709/
> feat(templates): Add a default Apache 2.0 license to tap and target templates

- samples/sample_tap_gitlab/schemas/epic_issues.json
- samples/sample_tap_gitlab/schemas/issues.json
- singer_sdk/testing/suites.py
- singer_sdk/testing/tap_tests.py
Failure example:
```
FAILED tests/external/test_tap_gitlab.py::TestSampleTapGitlab::test_tap_stream_record_matches_stream_schema[epic_issues] - AssertionError: Record does not match stream schema: '2021-11-03T15:21:07.350Z' is not of type 'null' (path: closed_at)
'flow::Review' is not of type 'object' (path: labels.0)
'kind::Feature' is not of type 'object' (path: labels.1)
'valuestream::Hub' is not of type 'object' (path: labels.2)
'2021-11-05' is not of type 'null' (path: milestone.due_date)
'2021-10-30' is not of type 'null' (path: milestone.start_date)
'project_id' is a required property (path: milestone)
FAILED tests/external/test_tap_gitlab.py::TestSampleTapGitlab::test_tap_stream_record_matches_stream_schema[issues] - AssertionError: Record does not match stream schema: {'id': …
```
> feat: Validate records against stream schema in standard tap tests

- docs/guides/pagination-classes.md
See https://github.com/MeltanoLabs/tap-klaviyo/pull/14#discussion_r1200898728
----
:books: Documentation preview :books:: https://meltano-sdk--1721.org.readthedocs.build/en/1721/
> docs: Remove unsupported `previous_token` from HATEOAS example

- .github/workflows/test.yml
https://github.com/codecov/codecov-action#arguments
----
:books: Documentation preview :books:: https://meltano-sdk--1729.org.readthedocs.build/en/1729/
> ci: Fail CI if upload to Codecov fails

- singer_sdk/streams/sql.py
Schema is called at least once per record and does not change within a stream, so it should be cached for performance benefits.
https://app.slack.com/client/TFG99TU9K/C013Z450LCD/thread/C013Z450LCD-1685703921.187269
----
:books: Documentation preview :books:: https://meltano-sdk--1745.org.readthedocs.build/en/1745/
> refactor(taps): Change `SQLStream.schema` into a cached property

- samples/sample_target_csv/csv_target_sink.py
- samples/sample_target_parquet/parquet_target_sink.py
- singer_sdk/testing/__init__.py
- singer_sdk/testing/factory.py
- singer_sdk/testing/runners.py
- singer_sdk/testing/target_tests.py
- tests/samples/test_target_parquet.py
----
:books: Documentation preview :books:: https://meltano-sdk--1752.org.readthedocs.build/en/1752/
> fix: change runner scope to function for target tests

- singer_sdk/typing.py
- tests/core/test_typing.py
Closes https://github.com/meltano/sdk/issues/1774
I added tests that I let run in CI and they fail https://github.com/meltano/sdk/actions/runs/5315601259/jobs/9624162264 then I pushed the change that fixes them.
----
:books: Documentation preview :books:: https://meltano-sdk--1775.org.readthedocs.build/en/1775/
> fix: Add tests for SQL type conversion from JSON schemas

- singer_sdk/sinks/core.py
- singer_sdk/target_base.py
- tests/conftest.py
- tests/core/test_target_base.py
- tests/samples/test_target_csv.py
Closes https://github.com/meltano/sdk/issues/1777
- moves test mock classes from the csv test to conftest so its reusable. Let me know if this should go somewhere else.
- adds test for target_base get_sink method to assert that when add_metadata_columns is used it doesnt affect the comparison. The [tests fail in CI](https://github.com/meltano/sdk/actions/runs/5326800321/jobs/9649332587) at first, then pass once I added a fix
- I chose to fix it by adding an original_schema attribute to the sink object. The alternative, and what I did in target-snowflake originally, is to add logic to remove those columns before doing the comparison but that sounded like more work.
@edgarrmondragon let me know what you think!
----
:books: Documentation preview :books:: …
> fix: Sink schema comparison before adding metadata columns

- singer_sdk/target_base.py
From a (private) [Slack conversation](https://meltano.slack.com/archives/C05FP72408K/p1688678721243459), it seems that we're missing the SCHEMA message count which makes it seem that the total is missing something.
Example of new output:
```
2023-07-07 12:46:08,109 | INFO     | target-csv           | Target 'target-csv' completed reading 262 lines of input (2 schemas, 257 records, 0 batch manifests, 3 state messages).
```
> fix(targets): Include SCHEMA message count in target logs

- poetry.lock
- pyproject.toml
Closes #1822
----
:books: Documentation preview :books:: https://meltano-sdk--1827.org.readthedocs.build/en/1827/
> fix: Add explicit dependency on `packaging` library

- singer_sdk/streams/rest.py
The gap was noted in a [slack conversation](https://meltano.slack.com/archives/CMN8HELB0/p1688963575249309).
https://meltano-sdk--1824.org.readthedocs.build/en/1824/classes/singer_sdk.RESTStream.html#singer_sdk.RESTStream.rest_method
> docs: Document `RESTStream.rest_method`

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{%if 'Apache-2.0' == cookiecutter.license %}LICENSE{%endif%}
- cookiecutter/target-template/{{cookiecutter.target_id}}/{%if 'Apache-2.0' == cookiecutter.license %}LICENSE{%endif%}
Addresses
- #1828 
Assigns copyright in the current year (not 2021) and to the `admin_name` set in the cookiecutter workflow.
---
Should this be merged, I'd happily submit a PR to do the same for:
- #1807 
This is, of course, conditional on whether or not we want to encourage MIT licensing within the Meltano/Singer community (as Apache-2 comes with explicit patent usage license, whereas MIT does not).
Closes #1828
----
:books: Documentation preview :books:: https://meltano-sdk--1829.org.readthedocs.build/en/1829/
> fix(templates): Update cookiecutter copyright assignment to cookiecutter user

- singer_sdk/authenticators.py
Adding support for adding a header to an OAuth request for tokens. In a few instances an API has a requirement to have headers added to the request for an OAuth Token. An example of the type of header is a subscription key.
This extends the current OAuth Authenticator to accept a new **optional** parameter `oauth_headers`.
The PR also explicitly converts the returned `expires_in` value to int rather than assuming it is an integer. I had an example where it was returned as an string from this API.
----
:books: Documentation preview :books:: https://meltano-sdk--1815.org.readthedocs.build/en/1815/
> feat: Support optional headers for OAuth request

- singer_sdk/plugin_base.py
- singer_sdk/tap_base.py
- singer_sdk/target_base.py
- tests/core/test_plugin_base.py
Closes #1821
----
:books: Documentation preview :books:: https://meltano-sdk--1835.org.readthedocs.build/en/1835/
> fix(taps): Avoid setting up mapper in discovery mode

- cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/{% if cookiecutter.include_ci_files == 'GitHub' %}test.yml{%endif%}
- poetry.lock
- pyproject.toml
```
Unable to create file '.github/workflows/{% if cookiecutter.include_ci_files == 'GitHub' %}test.yml{%endif%}'
Error message: 'collections.OrderedDict object' has no attribute 'tap_id'
```
----
:books: Documentation preview :books:: https://meltano-sdk--1843.org.readthedocs.build/en/1843/
> fix: Target template should not reference `tap_id`

- docs/cli_commands.md
Closes #321
----
:books: Documentation preview :books:: https://meltano-sdk--1852.org.readthedocs.build/en/1852/
> docs: Fix stale `pip_url` example that uses shell script workaround for editable installation

- singer_sdk/sinks/core.py
- tests/conftest.py
- tests/core/test_target_base.py
Related:
* Closes: https://github.com/meltano/sdk/issues/1819
cc @pnadolny13
----
:books: Documentation preview :books:: https://meltano-sdk--1853.org.readthedocs.build/en/1853/
> fix(targets): Check against the unconformed key properties when validating record keys

- singer_sdk/tap_base.py
- tests/samples/conftest.py
- tests/samples/test_tap_sqlite.py
Fixes the broken initialization of SQL taps following https://github.com/meltano/sdk/pull/1835.
The subclass initializer doesn't introduce any new arguments, so this PR changes it to use `*args` and `**kwargs` so we don't miss any changes to the parent class' initializer.
cc @BuzzCutNorman
----
:books: Documentation preview :books:: https://meltano-sdk--1842.org.readthedocs.build/en/1842/
> fix: Ensure all expected tap parameters are passed to `SQLTap` initializer

- docs/deprecation.md
- singer_sdk/testing/__init__.py
- tests/core/test_testing.py
In preparation for https://github.com/meltano/sdk/issues/1354 in v1
----
:books: Documentation preview :books:: https://meltano-sdk--1838.org.readthedocs.build/en/1838/
> fix: Add deprecation warning when importing legacy testing helpers

- pyproject.toml
- singer_sdk/connectors/sql.py
- tests/core/test_connector_sql.py
Closes https://github.com/meltano/sdk/issues/1897
----
:books: Documentation preview :books:: https://meltano-sdk--1898.org.readthedocs.build/en/1898/
> fix(targets): Correctly serialize `decimal.Decimal` in JSON fields of SQL targets

- cookiecutter/mapper-template/cookiecutter.json
- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
- cookiecutter/tap-template/cookiecutter.json
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- cookiecutter/target-template/cookiecutter.json
- cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
- docs/dev_guide.md
- e2e-tests/cookiecutters/mapper-base.json
- e2e-tests/cookiecutters/tap-graphql-jwt.json
- e2e-tests/cookiecutters/tap-other-custom.json
- e2e-tests/cookiecutters/tap-rest-api_key-github.json
- e2e-tests/cookiecutters/tap-rest-basic_auth.json
- e2e-tests/cookiecutters/tap-rest-bearer_token.json
- e2e-tests/cookiecutters/tap-rest-custom.json
- e2e-tests/cookiecutters/tap-rest-jwt.json
- e2e-tests/cookiecutters/tap-rest-oauth2.json
- e2e-tests/cookiecutters/tap-sql-custom.json
- e2e-tests/cookiecutters/target-per_record.json
- e2e-tests/cookiecutters/target-sql.json
Minor improvements spotted after using the tap template to test https://github.com/meltano/sdk/pull/1894:
- Added an `admin_email` field that's used in the `authors` filed in project metadata
- Added a note on using `~/.cookiecutterrc` to customize default values: https://meltano-sdk--1905.org.readthedocs.build/en/1905/dev_guide.html#building-a-new-tap-or-target
- Added human-readable prompts and make use of Rich markup:
----
:books: Documentation preview :books:: https://meltano-sdk--1905.org.readthedocs.build/en/1905/
> feat(templates): Add email field and use human-readable questions in templates

- singer_sdk/testing/factory.py
- tests/core/test_testing.py
Related:
* Closes https://github.com/meltano/sdk/issues/1912
> fix: Fix tap tests for multiple test classes with different input catalogs

- singer_sdk/exceptions.py
- singer_sdk/streams/core.py
- tests/core/test_streams.py
Closes: #1332
Changes:
- Add new `InvalidReplicationKeyException` to `singer_sdk.exceptions`
- Update `streams.core`. A `get()` is used to obtain the `replication_key` from `self.schema`, if the key is not present in the schema, the variable `type_dict` would equal `None`. A check has been added, if the value of the `type_dict` is `None` then the new exception is raised
- The resulting error message is of the format:
```log
"incorrect_replication_key" is not in schema for stream name: my_stream"
```
- Add a test to `tests/core/test_streams.py` which checks that a `SimpleTestStream` with `replication_key` overridden to `"INVALID"` raises the correct `InvalidReplicationKeyException` exception.
> fix: Handle replication key not found in stream schema

- samples/sample_tap_sqlite/__init__.py
- singer_sdk/streams/sql.py
- tests/samples/conftest.py
- tests/samples/test_tap_sqlite.py
- tests/samples/test_target_sqlite.py
----
:books: Documentation preview :books:: https://meltano-sdk--1951.org.readthedocs.build/en/1951/
> fix: Ensure SQL streams are sorted when a replication key is set

- noxfile.py
- poetry.lock
- pyproject.toml
- singer_sdk/connectors/sql.py
- tests/core/test_connector_sql.py
adds begin() to three other functions where schema is added or columns are altered. because of the changes made to auto-commit in SQLAlchemy 2.0, without begin() the ddl is rolled back.
matches style used in _create_empty_column()
----
:books: Documentation preview :books:: https://meltano-sdk--1954.org.readthedocs.build/en/1954/
> fix(targets): missing begin()s related to SQLAlchemy 2.0

- singer_sdk/mapper.py
Closes https://github.com/meltano/sdk/issues/1961
When trying to figure out how to fix https://github.com/meltano/sdk/issues/1961 I realized it was caused by the [raw_schema](https://github.com/meltano/sdk/blob/97d97de313511be4c21b842bf2ba0283d4bf5c02/singer_sdk/mapper.py#L87) in the mapper being a shared object with the [transformed_schema](https://github.com/meltano/sdk/blob/97d97de313511be4c21b842bf2ba0283d4bf5c02/singer_sdk/mapper.py#L89) which is passed to `get_sink` then `add_sink`, ultimately to the sink itself [where SDC columns are added](https://github.com/meltano/sdk/blob/97d97de313511be4c21b842bf2ba0283d4bf5c02/singer_sdk/sinks/core.py#L76). The rest of the codebase expects transformed_schema to be mutable but raw_schema to be immutable (or at least it reads that way to me). …
> perf: Ensure `raw_schema` in stream mapper is immutable

- pyproject.toml
- singer_sdk/connectors/sql.py
----
:books: Documentation preview :books:: https://meltano-sdk--1977.org.readthedocs.build/en/1977/
> fix: Fix hanging downstream tests in tap-postgres

- docs/code_samples.md
- poetry.lock
- pyproject.toml
- singer_sdk/helpers/_catalog.py
- singer_sdk/helpers/jsonpath.py
- tests/core/rest/conftest.py
- tests/core/test_mapper.py
----
:books: Documentation preview :books:: https://meltano-sdk--1981.org.readthedocs.build/en/1981/
> refactor: Use `functools.lru_cache` instead of the stale `memoization` library

- noxfile.py
- poetry.lock
- pyproject.toml
- tests/core/sinks/test_sdc_metadata.py
- tests/core/test_mapper.py
- tests/samples/test_tap_sqlite.py
- tests/samples/test_target_csv.py
| | [freezegun](https://pypi.org/project/freezegun/) | [time-machine](https://pypi.org/project/time-machine/) |
|-|-|-|
| Last released | Aug 12, 2022 | Sep 19, 2023 |
| Officially supported Python | 3.6 - 3.9 | 3.8 - 3.12 |
----
:books: Documentation preview :books:: https://meltano-sdk--1997.org.readthedocs.build/en/1997/
> test: Replace freezegun with time-machine

- singer_sdk/helpers/jsonpath.py
----
:books: Documentation preview :books:: https://meltano-sdk--1999.org.readthedocs.build/en/1999/
> feat(taps): Log JSONPatch match count at the INFO level

- CHANGELOG.md
- noxfile.py
- poetry.lock
- pyproject.toml
----
:books: Documentation preview :books:: https://meltano-sdk--2005.org.readthedocs.build/en/2005/
> chore: Drop dev dependency on meltano/commitizen-version-bump

- singer_sdk/_singerlib/messages.py
- tests/_singerlib/test_messages.py
Closes #1902 
----
:books: Documentation preview :books:: https://meltano-sdk--2006.org.readthedocs.build/en/2006/
> fix: Parse record `time_extracted` into `datetime.datetime` instance

- .github/workflows/test.yml
- noxfile.py
- poetry.lock
- pyproject.toml
- tests/core/test_mapper.py
relates to https://github.com/meltano/sdk/issues/2002.
As suggested in https://github.com/meltano/sdk/issues/2002#issuecomment-1751826751, 
This PR adds a benchmark test using pytest-benchmark to test the performance of stream maps using simpleeval, and ensure that we do not harm application performance by using `EvalWithCompoundTypes`.
The PR does the following:
* separate some logic into function `_run_transform` out of `_test_transform` to use for benchmarking
* add a benchmark test for the `repositories` stream with stream size of 4000 records
* add `pytest-benchmark` as a development dependency 
* add nox session for benchmarking (`benches`)
_I'm less sure if I've implemented the following two correctly as I'm not familiar with github actions_
* add `benches to the github-actions …
> test(taps): Add benchmark test on map transforms via `pytest-benchmark`

- docs/stream_maps.md
See https://meltano-sdk--2017.org.readthedocs.build/en/2017/stream_maps.html#compound-expressions
----
:books: Documentation preview :books:: https://meltano-sdk--2017.org.readthedocs.build/en/2017/
> docs: Document support for comprehenions in stream maps

- .github/workflows/codeql-analysis.yml
- docs/stream_maps.md
Closes https://github.com/meltano/sdk/issues/717
----
:books: Documentation preview :books:: https://meltano-sdk--2037.org.readthedocs.build/en/2037/
> docs: Add flattening configuration examples

- singer_sdk/_singerlib/catalog.py
- singer_sdk/authenticators.py
- singer_sdk/connectors/sql.py
- singer_sdk/helpers/_conformers.py
- singer_sdk/helpers/_flattening.py
- singer_sdk/helpers/_state.py
- singer_sdk/helpers/_typing.py
- singer_sdk/io_base.py
- singer_sdk/mapper.py
- singer_sdk/metrics.py
- singer_sdk/sinks/core.py
- singer_sdk/sinks/sql.py
- singer_sdk/tap_base.py
- singer_sdk/target_base.py
- singer_sdk/testing/factory.py
- singer_sdk/testing/legacy.py
- singer_sdk/typing.py
----
:books: Documentation preview :books:: https://meltano-sdk--2052.org.readthedocs.build/en/2052/
> chore: Fix some docstring typos and apply refactors suggested by Sourcery

- .github/ISSUE_TEMPLATE/bug.yml
- .github/workflows/codspeed.yml
- .github/workflows/cookiecutter-e2e.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/version_bump.yml
- noxfile.py
----
:books: Documentation preview :books:: https://meltano-sdk--2062.org.readthedocs.build/en/2062/
> ci: Use Python 3.11 as the default Python version in CI jobs

- singer_sdk/testing/factory.py
- singer_sdk/testing/suites.py
----
:books: Documentation preview :books:: https://meltano-sdk--2056.org.readthedocs.build/en/2056/
> refactor: Break up `TapTestClassFactory._annotate_test_class` into simpler methods

- tests/core/sinks/test_validation.py
Benchmark run time drops from ~9 to ~2 minutes.
cc @buzzcutnorman
----
:books: Documentation preview :books:: https://meltano-sdk--2064.org.readthedocs.build/en/2064/
> chore: Faster benchmarks

- .github/semantic.yml
- poetry.lock
- pyproject.toml
Currently we have a _transitive_ dependency on
[`python-dateutil`](https://github.com/dateutil/dateutil) via [`pendulum`](https://github.com/sdispater/pendulum).
We actually rely on direct calls to its API, so it's better to list it as an explicit dependency in order not to break more stuff than necessary if we ever remove the dependency on Pendulum.
----
:books: Documentation preview :books:: https://meltano-sdk--2076.org.readthedocs.build/en/2076/
> fix(deps): Make a explicit dependency on `python-dateutil`

- pyproject.toml
----
:books: Documentation preview :books:: https://meltano-sdk--2079.org.readthedocs.build/en/2079/
> chore: Use `exclude_also` in coverage config

- samples/sample_tap_google_analytics/ga_tap_stream.py
- singer_sdk/_singerlib/messages.py
- singer_sdk/_singerlib/utils.py
- singer_sdk/testing/tap_tests.py
----
:books: Documentation preview :books:: https://meltano-sdk--2092.org.readthedocs.build/en/2092/
> refactor: Use `datetime.fromisoformat` in other places

- singer_sdk/streams/sql.py
----
:books: Documentation preview :books:: https://meltano-sdk--2095.org.readthedocs.build/en/2095/
> refactor(taps): Use `CursorResult.mappings()` in SQL streams

- .github/workflows/test.yml
- noxfile.py
- poetry.lock
- pyproject.toml
- singer_sdk/authenticators.py
- tests/core/rest/test_pagination.py
- tests/core/test_connector_sql.py
Blockers:
----
:books: Documentation preview :books:: https://meltano-sdk--1733.org.readthedocs.build/en/1733/
> feat: Test with Python 3.12 🐍

- .pre-commit-config.yaml
- noxfile.py
- pyproject.toml
- singer_sdk/authenticators.py
- singer_sdk/connectors/sql.py
- singer_sdk/helpers/_flattening.py
- singer_sdk/pagination.py
- singer_sdk/streams/rest.py
- singer_sdk/typing.py
----
📚 Documentation preview 📚: https://meltano-sdk--2104.org.readthedocs.build/en/2104/
> chore: Use Ruff to format docstrings

- singer_sdk/helpers/jsonpath.py
Adding the expression to the jsonpath logging message can be helpful in determining whether the message refers to a "next page" jsonpath parsing call, or a "records" parsing call
----
📚 Documentation preview 📚: https://meltano-sdk--2118.org.readthedocs.build/en/2118/
> fix: Output JSONPath expression with match count message

- .github/workflows/codspeed.yml
----
📚 Documentation preview 📚: https://meltano-sdk--2134.org.readthedocs.build/en/2134/
> ci: Use Python 3.12 to compute benchmarks

- docs/code_samples.md
----
📚 Documentation preview 📚: https://meltano-sdk--2140.org.readthedocs.build/en/2140/
> docs: Update auth caching example to use `functools.cached_property`

- docs/guides/pagination-classes.md
- singer_sdk/pagination.py
- singer_sdk/streams/rest.py
- tests/core/rest/test_pagination.py
----
:books: Documentation preview :books:: https://meltano-sdk--1918.org.readthedocs.build/en/1918/
> feat(taps): End RESTStream pagination if an empty page is received

- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/tests/conftest.py
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/tests/conftest.py
- cookiecutter/target-template/{{cookiecutter.target_id}}/tests/conftest.py
- docs/testing.md
- pyproject.toml
- tests/conftest.py
----
📚 Documentation preview 📚: https://meltano-sdk--2158.org.readthedocs.build/en/2158/
> fix: Fix pytest plugin declaration so it can be used without requiring declaration of `pytest_plugins`

- .github/ISSUE_TEMPLATE/bug.yml
- .github/workflows/test.yml
- docs/CONTRIBUTING.md
- noxfile.py
- poetry.lock
- pyproject.toml
- singer_sdk/connectors/sql.py
- singer_sdk/helpers/_compat.py
- singer_sdk/helpers/_state.py
- singer_sdk/helpers/_typing.py
- singer_sdk/io_base.py
- singer_sdk/pagination.py
- singer_sdk/plugin_base.py
- singer_sdk/sinks/core.py
- singer_sdk/sinks/record.py
- singer_sdk/streams/core.py
- singer_sdk/streams/sql.py
- singer_sdk/tap_base.py
- singer_sdk/target_base.py
Backport from the V1 branch to maybe ship this earlier?
----
📚 Documentation preview 📚: https://meltano-sdk--2143.org.readthedocs.build/en/2143/
> refactor: Drop support for Python 3.7

- .pre-commit-config.yaml
- cookiecutter/.gitignore
- cookiecutter/tap-template/hooks/post_gen_project.py
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/.vscode/launch.json
Closes https://github.com/meltano/sdk/issues/2182
----
📚 Documentation preview 📚: https://meltano-sdk--2183.org.readthedocs.build/en/2183/
> fix(templates): Ensure `.vscode` directory is included when requested in cookiecutters and avoid failing if it does not exist

- docs/conf.py
- docs/dev_guide.md
See https://github.com/meltano/sdk/issues/2182#issuecomment-1912321145
----
📚 Documentation preview 📚: https://meltano-sdk--2186.org.readthedocs.build/en/2186/
> docs: Call out minimum recommended `cookiecutter` version

- singer_sdk/helpers/_catalog.py
- singer_sdk/mapper.py
- singer_sdk/streams/core.py
- singer_sdk/streams/sql.py
- tests/core/test_catalog_selection.py
- tests/samples/test_tap_countries.py
----
📚 Documentation preview 📚: https://meltano-sdk--2188.org.readthedocs.build/en/2188/
> refactor: Remove unused `logger` parameter from private catalog helper functions

- poetry.lock
- pyproject.toml
- singer_sdk/helpers/_catalog.py
- singer_sdk/helpers/jsonpath.py
- tests/core/rest/conftest.py
- tests/core/test_mapper.py
----
📚 Documentation preview 📚: https://meltano-sdk--2189.org.readthedocs.build/en/2189/
> refactor: Use `functools.lru_cache` instead of the stale `memoization` library (#1981)

- cookiecutter/tap-template/hooks/post_gen_project.py
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/schemas/__init__.py
----
📚 Documentation preview 📚: https://meltano-sdk--2195.org.readthedocs.build/en/2195/
> fix(templates): Include empty `schemas` directory in REST tap cookiecutter

- pyproject.toml
- samples/sample_tap_gitlab/gitlab_rest_streams.py
- samples/sample_tap_gitlab/schemas/issues.json
- samples/sample_tap_gitlab/schemas/projects.json
- samples/sample_tap_gitlab/schemas/releases.json
- samples/sample_tap_google_analytics/schemas/simple-sample.json
- tests/core/test_connector_sql.py
----
📚 Documentation preview 📚: https://meltano-sdk--2197.org.readthedocs.build/en/2197/
> test: Fail on unhandled warnings

- singer_sdk/sinks/sql.py
- tests/samples/test_target_sqlite.py
- Update sql.py
- Mattwill09 patch 1 (#1)
- Update singer_sdk/sinks/sql.py
- Use IdentifierPreparer
----
📚 Documentation preview 📚: https://meltano-sdk--2200.org.readthedocs.build/en/2200/
> fix(targets): Quote column names in INSERT statement

- docs/batch.md
- docs/conf.py
- docs/dev_guide.md
- singer_sdk/authenticators.py
- singer_sdk/pagination.py
- singer_sdk/plugin_base.py
- singer_sdk/streams/rest.py
----
📚 Documentation preview 📚: https://meltano-sdk--2204.org.readthedocs.build/en/2204/
> docs: Document supported package extras

- singer_sdk/helpers/capabilities.py
- singer_sdk/sinks/core.py
- singer_sdk/target_base.py
- tests/core/test_target_base.py
Related:
* Closes https://github.com/meltano/sdk/issues/1904
----
📚 Documentation preview 📚: https://meltano-sdk--2208.org.readthedocs.build/en/2208/
> feat(targets): Allow users to disable schema validation in targets

- noxfile.py
- poetry.lock
- pyproject.toml
- singer_sdk/sinks/core.py
- tests/core/sinks/test_validation.py
Supersedes https://github.com/meltano/sdk/pull/2066
Co-authored-by: Dan Norman <buzzcutnorman@gmail.com>
----
📚 Documentation preview 📚: https://meltano-sdk--2231.org.readthedocs.build/en/2231/
> docs: Added an example implemetation of JSON schema validation that uses `fastjsonschema`

- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/test.yml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/test.yml
- cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/test.yml
Closes #2223
----
📚 Documentation preview 📚: https://meltano-sdk--2232.org.readthedocs.build/en/2232/
> fix(templates): Test workflow job now fails for unsupported Python versions in cookiecutter templates

- singer_sdk/connectors/sql.py
Soft delete is deleting only versions smaller than the latest version .
Hard delete is deleting smaller and equal.
Making both strategies delete only smaller versions.
fixes https://github.com/meltano/sdk/issues/2227
----
📚 Documentation preview 📚: https://meltano-sdk--2242.org.readthedocs.build/en/2242/
> fix(taps): Hard and soft deletes for handling `ACTIVATE_VERSION` messages now use the same `WHERE` clause 

- singer_sdk/helpers/_typing.py
- tests/core/test_typing.py
Closes #1887 
----
📚 Documentation preview 📚: https://meltano-sdk--2245.org.readthedocs.build/en/2245/
> fix: Instances of `oneOf` are now handled by null-appending logic

- singer_sdk/helpers/_typing.py
- tests/core/test_typing.py
This was causing config validation failures in `meltano-map-transform`: https://github.com/MeltanoLabs/meltano-map-transform/actions/runs/7962941688/job/21737507548?pr=221
> fix: Null type is now correctly appended as `{"type": "null"}` to `oneOf` types

- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/test.yml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/test.yml
- cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/test.yml
Follow-up from #2232 
---
The current test workflow configuration for the `pytest` job uses `continue-on-error: true`, meaning that when any matrix job (i.e. test run for a specific Python version) fails, the workflow itself still shows as passing - for example: https://github.com/Matatika/tap-spotify/actions/runs/8089702498
[`fail-fast: false`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) is what should have been implemented initially (sorry, still fairly new to GitHub Actions) - for example: https://github.com/Matatika/tap-spotify/actions/runs/8089862693
----
📚 Documentation preview 📚: https://meltano-sdk--2274.org.readthedocs.build/en/2274/
> fix(templates): Test workflow now fails for any Python matrix job failure in cookiecutter template

- .github/workflows/version_bump.yml
Related:
- https://github.com/commitizen-tools/commitizen/issues/1024
----
📚 Documentation preview 📚: https://meltano-sdk--2314.org.readthedocs.build/en/2314/
> chore: Fix version bump

- .github/workflows/version_bump.yml
It was patched in https://github.com/commitizen-tools/commitizen/pull/1026
----
📚 Documentation preview 📚: https://meltano-sdk--2317.org.readthedocs.build/en/2317/
> chore(deps): Unpin `commitizen` to use latest patch in version bump

- docs/capabilities.rst
> Is it enough that a tap is built with the SDK for it to support batched files (i.e. `batch` capability)? [These docs](https://sdk.meltano.com/en/latest/capabilities.html#singer_sdk.helpers.capabilities.PluginCapabilities.BATCH) seem to suggest it requires an implementation, but the SDK reports it as a supported capability with `--about`...
https://meltano.slack.com/archives/C068YBV6KEK/p1710531278261849
----
📚 Documentation preview 📚: https://meltano-sdk--2326.org.readthedocs.build/en/2326/
> docs: Documented `BATCH` as a default plugin capability

- cookiecutter/mapper-template/hooks/post_gen_project.py
- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
- cookiecutter/target-template/hooks/post_gen_project.py
- cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml
Related to #2182 and #2183
These templates currently do not have a `.vscode` directory, and so when VSCode IDE config is not requested (i.e. `2 - None` option) the post generate project hook fails trying to remove a directory that doesn't exist:
```
FileNotFoundError: [Errno 2] No such file or directory: '.vscode'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
```
This PR simply ignores that error for target and mapper templates, should it occur. I haven't added any VSCode config (e.g. `launch.json`) as it's probably not gonna be the same as the tap template (in hindsight, I might have been a bit quick to exclude `launch.json` from the `check-json` pre-commit hook).
> fix(templates): Avoid failing if VSCode IDE config is not requested for target and mapper cookiecutter templates

- singer_sdk/typing.py
- tests/core/test_typing.py
In `tap-spotify`, all schema objects inherit from [a `CustomObject` class](https://github.com/Matatika/tap-spotify/blob/a816614ef79d94de8f96948df3cc81ad3e4656f6/tap_spotify/schemas/utils/custom_object.py) that offers some convenience methods, including allowing [one custom object to extend others](https://github.com/Matatika/tap-spotify/blob/master/tap_spotify/streams.py#L125) in order to produce a merged schema. The reason this class exists was because at the time there wasn't an obvious way to merge two or more property lists together, but I think its a pretty simple addition to get the functionality natively.
Given that, for example, [`Rank`](https://github.com/Matatika/tap-spotify/blob/a816614ef79d94de8f96948df3cc81ad3e4656f6/tap_spotify/schemas/utils/rank.py), …
> feat: `PropertiesList` can now behave as an iterable

- singer_sdk/sinks/core.py
If schema flattening is enabled but a value for a key in the record which is flattened is None, this warning is returned because the record can not be flattened and then the key is not in the schema. This can be avoided by checking if the value is None. If it is None the record field actually does not exist so we do not need a warning.
----
📚 Documentation preview 📚: https://meltano-sdk--2348.org.readthedocs.build/en/2348/
> fix(targets): Added a condition to the `No schema for record field` warning

- .github/workflows/cookiecutter-e2e.yml
- .github/workflows/test.yml
----
📚 Documentation preview 📚: https://meltano-sdk--2358.org.readthedocs.build/en/2358/
> ci: Qualify constraints file with workspace directory

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- docs/deprecation.md
- docs/dev_guide.md
- noxfile.py
- poetry.lock
- pyproject.toml
- singer_sdk/authenticators.py
refactor: Added a `jwt` package extra. The `cryptography` and `PyJWT` dependencies is not yet removed from the default dependencies
----
📚 Documentation preview 📚: https://meltano-sdk--2205.org.readthedocs.build/en/2205/
> refactor: Added a `jwt` package extra, but the `cryptography` and `jwt` dependencies are still installed by default for now

- pyproject.toml
- singer_sdk/exceptions.py
- singer_sdk/helpers/_catalog.py
- singer_sdk/io_base.py
- singer_sdk/plugin_base.py
- singer_sdk/sinks/core.py
- singer_sdk/streams/core.py
- singer_sdk/streams/rest.py
- singer_sdk/tap_base.py
- singer_sdk/target_base.py
- singer_sdk/testing/tap_tests.py
- singer_sdk/typing.py
----
📚 Documentation preview 📚: https://meltano-sdk--2264.org.readthedocs.build/en/2264/
> chore: Enable `TRY` and `FLY` Ruff rules

- .github/workflows/constraints.txt
- noxfile.py
* https://github.com/wntrblm/nox/releases/tag/2024.04.15
* https://nox.thea.codes/en/stable/tutorial.html#loading-dependencies-from-pyproject-toml-or-scripts
* https://nox.thea.codes/en/stable/config.html#nox-version-requirements
> chore: Use `nox.project.load_toml` to get test dependencies

- .github/workflows/test.yml
- noxfile.py
Would be nice to have:
* https://github.com/astral-sh/uv/issues/2231
* https://github.com/actions/setup-python/pull/818
----
📚 Documentation preview 📚: https://meltano-sdk--2377.org.readthedocs.build/en/2377/
> ci: Use uv in CI

- singer_sdk/_singerlib/schema.py
- singer_sdk/helpers/_typing.py
- singer_sdk/typing.py
- tests/_singerlib/test_schema.py
- tests/core/test_jsonschema_helpers.py
----
📚 Documentation preview 📚: https://meltano-sdk--2389.org.readthedocs.build/en/2389/
> feat: JSON schema keyword `allOf` is now supported

- pyproject.toml
----
📚 Documentation preview 📚: https://meltano-sdk--2391.org.readthedocs.build/en/2391/
> chore: Bump `poetry-core` build backend to 1.9

- poetry.lock
----
📚 Documentation preview 📚: https://meltano-sdk--2397.org.readthedocs.build/en/2397/
> chore: Run `poetry lock` to install the latest transitive dependencies

- .github/workflows/test.yml
Related:
* #2390 
----
📚 Documentation preview 📚: https://meltano-sdk--2398.org.readthedocs.build/en/2398/
> ci: Back to `macos-latest` in test workflows

- singer_sdk/sinks/core.py
----
📚 Documentation preview 📚: https://meltano-sdk--2421.org.readthedocs.build/en/2421/
> fix: An error message is now logged every time schema validation fails for any record

- .pre-commit-config.yaml
- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/build.yml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/build.yml
- cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/build.yml
- samples/sample_tap_gitlab/schemas/epic_issues.json
----
📚 Documentation preview 📚: https://meltano-sdk--2426.org.readthedocs.build/en/2426/
> feat(templates): Added an optional GitHub workflow to publish to PyPI with trusted publishers

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/.vscode/launch.json
----
📚 Documentation preview 📚: https://meltano-sdk--2431.org.readthedocs.build/en/2431/
> fix(templates): Updated cookiecutter VSCode `launch.json` to use `debugpy`

- singer_sdk/streams/rest.py
----
📚 Documentation preview 📚: https://meltano-sdk--2433.org.readthedocs.build/en/2433/
> feat(taps): Tap developers can now disable HTTP redirects

- docs/stream_maps.md
----
📚 Documentation preview 📚: https://meltano-sdk--2435.org.readthedocs.build/en/2435/
> docs: Using an empty list for `__key_properties__` to disable a stream primary keys is now recommended as an alternative to `null`

- docs/dev_guide.md
- docs/guides/config-schema.md
- docs/guides/index.md
----
📚 Documentation preview 📚: https://meltano-sdk--2449.org.readthedocs.build/en/2449/
> docs: Add a short guide on defining a configuration schema

- poetry.lock
- pyproject.toml
----
📚 Documentation preview 📚: https://meltano-sdk--2451.org.readthedocs.build/en/2451/
> chore: Add python marker to `duckdb-engine` dev dependency

- singer_sdk/sinks/sql.py
- tests/core/test_record_typing.py
- tests/core/test_streams.py
----
📚 Documentation preview 📚: https://meltano-sdk--2454.org.readthedocs.build/en/2454/
> chore: Use `singer_sdk.helpers._util.utc_now` in ACTIVATE_VERSION handling

- singer_sdk/helpers/_typing.py
----
📚 Documentation preview 📚: https://meltano-sdk--2455.org.readthedocs.build/en/2455/
> refactor: Use parent `datetime.datetime` class in type conforming checks

- noxfile.py
- singer_sdk/about.py
- tests/core/test_about.py
- tests/snapshots/about_format/json.snap.json
- tests/snapshots/about_format/markdown.snap.md
- tests/snapshots/about_format/text.snap.txt
----
📚 Documentation preview 📚: https://meltano-sdk--2526.org.readthedocs.build/en/2526/
> fix: Moved up the supported Python versions in the Markdown output of `--about`

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/rest-client.py
----
📚 Documentation preview 📚: https://meltano-sdk--2528.org.readthedocs.build/en/2528/
> refactor(templates): Moved class-level attributes to the top in REST tap template

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/graphql-client.py
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/other-client.py
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/rest-client.py
- pyproject.toml
- singer_sdk/helpers/_state.py
- singer_sdk/helpers/types.py
- singer_sdk/metrics.py
- singer_sdk/streams/core.py
- singer_sdk/streams/graphql.py
- singer_sdk/streams/rest.py
- singer_sdk/streams/sql.py
Some context on the design here:
* Adding a `context` parameter to `RESTStream.get_new_paginator` is a breaking change. It could be handled by catching a `TypeError` and retrying the call without the parameter, but this feels unnecessarily complicated.
* I opted for adding a new `context` attribute to the `Stream` instance. It's only set when the sync starts and is wrapped by `MappingProxyType` to discourage mutating the context object.
* The above makes the `context` parameter accepted by some methods a bit redundant, but I'm unsure whether it's worth deprecating and eventually removing it.
* Docs: https://meltano-sdk--2529.org.readthedocs.build/en/2529/classes/singer_sdk.Stream.html#singer_sdk.Stream
----
📚 Documentation preview 📚: …
> feat: Stream sync context is now available to all instances methods as a `Stream.context` attribute

- poetry.lock
- pyproject.toml
- singer_sdk/authenticators.py
* A quick gathering of some data points from MeltanoLabs:
- 1 package relies on `jwt`:
- [tap-github](https://github.com/MeltanoLabs/tap-github/blob/1b41def4001c2111a8e7024aa94241759e9ba90e/tap_github/authenticator.py#L10), but it's already [an explicit dependency](https://github.com/MeltanoLabs/tap-github/blob/1b41def4001c2111a8e7024aa94241759e9ba90e/pyproject.toml#L27)
- 1 package relies on `cryptography`:
- [target-snowflake](https://github.com/MeltanoLabs/target-snowflake/blob/b357c52574380345e9253eace99989cd35787ca0/target_snowflake/connector.py#L8), but it's already [an explicit dependency](https://github.com/MeltanoLabs/target-snowflake/blob/b357c52574380345e9253eace99989cd35787ca0/pyproject.toml#L18)
* Matatika has 0 repos
* Automattic has 0 repos
* AutoIDM has 0 repos
* Hotglue …
> refactor!: Make `PyJWT` and `cryptography` dependencies optional

- docs/stream_maps.md
- singer_sdk/mapper.py
This allows using `json.loads()` and `json.dumps()` to convert fields between text and json representations.
Particularily useful moving data between MySQL and Postgres where MySQL stores json as text, and Postgres stores json as JSONB.
Usage in a stream_map:
```yaml
stream_maps:
sample-reports:
recipients_email_addresses: json.loads(recipients_email_addresses)
```
Closes https://github.com/meltano/sdk/issues/1502
----
📚 Documentation preview 📚: https://meltano-sdk--2531.org.readthedocs.build/en/2531/
> feat: The `json` module is now avaiable to stream maps

- docs/conf.py
- docs/stream_maps.md
----
📚 Documentation preview 📚: https://meltano-sdk--2535.org.readthedocs.build/en/2535/
> docs: Added more intersphinx links to Python and Faker docs

- docs/conf.py
I went ahead and enabled addons in
https://app.readthedocs.org/dashboard/meltano-sdk/addons/edit/ and
updated `docs/conf.py` following guidance from the blog post.
References:
* https://about.readthedocs.com/blog/2024/07/addons-by-default/
* https://docs.readthedocs.io/en/stable/pull-requests.html#features
* https://docs.readthedocs.io/en/stable/addons.html#enabling-read-the-docs-addons
----
📚 Documentation preview 📚: https://meltano-sdk--2536.org.readthedocs.build/en/2536/
> docs: Prepare for RTD addons migration

- samples/sample_duckdb/__init__.py
- samples/sample_duckdb/connector.py
- tests/core/sinks/test_sql_sink.py
- tests/core/test_connector_sql.py
----
📚 Documentation preview 📚: https://meltano-sdk--2548.org.readthedocs.build/en/2548/
> test: Add (DuckDB) SQL sink tests

- singer_sdk/target_base.py
Closes https://github.com/meltano/sdk/issues/1055
----
📚 Documentation preview 📚: https://meltano-sdk--2554.org.readthedocs.build/en/2554/
> fix: Use mapped stream aliases when handling `ACTIVATE_VERSION` messages in the base target class

- singer_sdk/about.py
- singer_sdk/plugin_base.py
- tests/core/test_about.py
- tests/snapshots/about_format/text.snap.txt
----
📚 Documentation preview 📚: https://meltano-sdk--2555.org.readthedocs.build/en/2555/
> chore: Split settings, python versions and capabilities into their own lines in plain about output

- singer_sdk/streams/core.py
----
📚 Documentation preview 📚: https://meltano-sdk--2557.org.readthedocs.build/en/2557/
> docs: Document that `get_starting_timestamp` requires setting a non-null replication_key

- samples/sample_target_sqlite/__init__.py
- singer_sdk/sinks/sql.py
- tests/conftest.py
----
📚 Documentation preview 📚: https://meltano-sdk--2564.org.readthedocs.build/en/2564/
> refactor: Make `SQLSink` a generic with a `SQLConnector` type parameter

- singer_sdk/helpers/types.py
----
📚 Documentation preview 📚: https://meltano-sdk--2575.org.readthedocs.build/en/2575/
> chore: Add a type parameter to `singer_sdk.helpers.types.Context`

- poetry.lock
- pyproject.toml
* pendulum: Closes https://github.com/meltano/sdk/issues/1858
* python-dateutil
----
📚 Documentation preview 📚: https://meltano-sdk--2520.org.readthedocs.build/en/2520/
> packaging!: Remove unused dependencies `pendulum` and `python-dateutil`

- singer_sdk/connectors/sql.py
call the `compile` method, specifying the sqlalchemy engine, this ensures that sqlalchemy is able to specify database specific object quoting.
----
📚 Documentation preview 📚: https://meltano-sdk--2582.org.readthedocs.build/en/2582/
> fix(target): DDL for adding a column now uses a SQLAlchemy-compiled clause to apply proper quoting

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/rest-client.py
- noxfile.py
- singer_sdk/helpers/types.py
- singer_sdk/streams/rest.py
----
📚 Documentation preview 📚: https://meltano-sdk--2586.org.readthedocs.build/en/2586/
> chore: Define `Auth` type alias in `types` module

- singer_sdk/about.py
- tests/snapshots/about_format/text.snap.txt
----
📚 Documentation preview 📚: https://meltano-sdk--2592.org.readthedocs.build/en/2592/
> fix: Fixed typos in `--about` plain text output

- docs/stream_maps.md
----
📚 Documentation preview 📚: https://meltano-sdk--2595.org.readthedocs.build/en/2595/
> docs: Documented examples of stream glob expressions and property aliasing

- singer_sdk/authenticators.py
Updated API docs (press `d` on the page to toggle the diff view):
- https://meltano-sdk--2596.org.readthedocs.build/en/2596/classes/singer_sdk.authenticators.OAuthAuthenticator.html#singer_sdk.authenticators.OAuthAuthenticator
- https://meltano-sdk--2596.org.readthedocs.build/en/2596/classes/singer_sdk.authenticators.APIAuthenticatorBase.html#singer_sdk.authenticators.APIAuthenticatorBase
Closes https://github.com/meltano/sdk/issues/925
----
📚 Documentation preview 📚: https://meltano-sdk--2596.org.readthedocs.build/en/2596/
> refactor: Made `auth_headers` and `auth_params` of `APIAuthenticatorBase` simple instance attributes instead of decorated properties

- singer_sdk/pagination.py
----
📚 Documentation preview 📚: https://meltano-sdk--2597.org.readthedocs.build/en/2597/
> refactor: Mark pagination classes with `@override` decorator

- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
- poetry.lock
- pyproject.toml
----
📚 Documentation preview 📚: https://meltano-sdk--2599.org.readthedocs.build/en/2599/
> refactor: Remove `pytest-durations` dependency from `testing` and use native pytest option `--durations`

- singer_sdk/connectors/sql.py
- singer_sdk/sinks/sql.py
- singer_sdk/streams/sql.py
- tests/core/test_connector_sql.py
Related:
- https://github.com/MeltanoLabs/target-snowflake/issues/230
- https://github.com/MeltanoLabs/target-snowflake/pull/232
- Blocks https://github.com/MeltanoLabs/target-snowflake/pull/242
----
📚 Documentation preview 📚: https://meltano-sdk--2601.org.readthedocs.build/en/2601/
> refactor: Improved SQL identifier (de)normalization

- singer_sdk/connectors/sql.py
- tests/core/test_connector_sql.py
Follows from #2601
----
📚 Documentation preview 📚: https://meltano-sdk--2603.org.readthedocs.build/en/2603/
> refactor: Backwards-compatible identifier quoting in fully qualified names

- singer_sdk/plugin_base.py
- singer_sdk/sinks/core.py
- singer_sdk/testing/suites.py
- singer_sdk/testing/tap_tests.py
- singer_sdk/typing.py
- tests/core/sinks/test_validation.py
- tests/core/test_jsonschema_helpers.py
----
📚 Documentation preview 📚: https://meltano-sdk--2567.org.readthedocs.build/en/2567/
> feat(taps): A new `schema_is_valid` built-in tap test validates stream schemas against the JSON Schema specification

- docs/code_samples.md
Related:
- Closes https://github.com/meltano/sdk/issues/728
- Closes https://github.com/meltano/sdk/issues/1588
----
📚 Documentation preview 📚: https://meltano-sdk--2604.org.readthedocs.build/en/2604/
> docs: Update project sample links

- .github/workflows/release.yml
----
📚 Documentation preview 📚: https://meltano-sdk--2581.org.readthedocs.build/en/2581/
> ci: Let us create lightweight pre-release tags

- singer_sdk/streams/core.py
- tests/core/test_streams.py
Related:
- Closes https://github.com/meltano/sdk/issues/2612
- https://github.com/meltano/sdk/issues/2612
----
📚 Documentation preview 📚: https://meltano-sdk--2613.org.readthedocs.build/en/2613/
> fix: Mismatch between timezone-aware and naive datetimes in start date and bookmarks is now correctly handled

- poetry.lock
- pyproject.toml
----
📚 Documentation preview 📚: https://meltano-sdk--2616.org.readthedocs.build/en/2616/
> test: Test with the latest numpy for pyarrow support

- singer_sdk/streams/core.py
Follow-on of https://github.com/meltano/sdk/pull/2613.
----
📚 Documentation preview 📚: https://meltano-sdk--2619.org.readthedocs.build/en/2619/
> refactor: Default to UTC when parsing dates without a known timezone

- singer_sdk/sinks/core.py
----
📚 Documentation preview 📚: https://meltano-sdk--2628.org.readthedocs.build/en/2628/
> refactor: Use context manager to read gzip batch files

- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/test.yml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/test.yml
- cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/test.yml
----
📚 Documentation preview 📚: https://meltano-sdk--2627.org.readthedocs.build/en/2627/
> chore: Use `paths` to filter triggers for test jobs in templates

- docs/incremental_replication.md
Updated docs: https://meltano-sdk--2629.org.readthedocs.build/en/2629/incremental_replication.html#example-code-timestamp-based-incremental-replication
----
📚 Documentation preview 📚: https://meltano-sdk--2629.org.readthedocs.build/en/2629/
> docs: Reference `get_starting_timestamp` in incremental replication guide

- .github/workflows/test.yml
----
📚 Documentation preview 📚: https://meltano-sdk--2638.org.readthedocs.build/en/2638/
> ci: Use `include-hidden-files: true` to upload coverage artifacts

- docs/stream_maps.md
Take a look: https://meltano-sdk--2639.org.readthedocs.build/en/2639/stream_maps.html#built-in-variable-names.
Motivation: https://github.com/MeltanoLabs/meltano-map-transform/issues/215#issuecomment-2324100873
----
📚 Documentation preview 📚: https://meltano-sdk--2639.org.readthedocs.build/en/2639/
> docs: Documented versions where `fake` and `Faker` objects were added to the stream maps context

- poetry.lock
- pyproject.toml
Less maintenance burden on our end. If `faker` makes a breaking change upstream, we would just catch it CI and make a patch release.
----
📚 Documentation preview 📚: https://meltano-sdk--2640.org.readthedocs.build/en/2640/
> packaging: Remove upper constraint on `faker` extra

- singer_sdk/authenticators.py
- singer_sdk/connectors/sql.py
- tests/core/test_connector_sql.py
- https://peps.python.org/pep-0702/
- https://docs.python.org/3.13/library/warnings.html#warnings.deprecated
- https://typing-extensions.readthedocs.io/en/latest/#typing_extensions.deprecated
----
📚 Documentation preview 📚: https://meltano-sdk--2647.org.readthedocs.build/en/2647/
> refactor: Use future `warnings.deprecated` decorator

- docs/classes/singer_sdk.connectors.sql.SQLToJSONSchema.rst
- docs/conf.py
- docs/guides/index.md
- docs/guides/sql-tap.md
- docs/reference.rst
- singer_sdk/connectors/sql.py
- singer_sdk/typing.py
- tests/core/test_connector_sql.py
- tests/core/test_sql_typing.py
Related:
- https://github.com/meltano/sdk/issues/1831
- https://github.com/TicketSwap/target-redshift/issues/105
- https://github.com/MeltanoLabs/tap-postgres/issues/477
- https://github.com/meltano/sdk/issues/1812
- https://github.com/MeltanoLabs/tap-postgres/pull/485
- https://github.com/thkwag/target-mysql/blob/c84fe01850b0470d39e4d0c56fd884e2019174c4/target_mysql/sinks.py#L195-L196
New docs links:
- Custom type mapping guide: https://meltano-sdk--2618.org.readthedocs.build/en/2618/guides/sql-tap.html#custom-type-mapping
- Default type mapping reference docs: https://meltano-sdk--2618.org.readthedocs.build/en/2618/classes/singer_sdk.connectors.sql.SQLToJSONSchema.html#singer_sdk.connectors.sql.SQLToJSONSchema
----
📚 Documentation preview 📚: …
> feat: Developers can now more easily override the mapping from SQL column type to JSON schema

- singer_sdk/connectors/sql.py
- singer_sdk/streams/sql.py
- tests/core/test_connector_sql.py
- tests/samples/conftest.py
- tests/samples/test_tap_sqlite.py
----
📚 Documentation preview 📚: https://meltano-sdk--2651.org.readthedocs.build/en/2651/
> feat(taps): SQL taps now emit schemas with `maxLength` when applicable

- docs/guides/sql-tap.md
- singer_sdk/connectors/sql.py
- singer_sdk/streams/rest.py
----
📚 Documentation preview 📚: https://meltano-sdk--2658.org.readthedocs.build/en/2658/
> docs: Added more versions when stuff changed or was added

- poetry.lock
- pyproject.toml
Closes https://github.com/meltano/sdk/issues/2659.
----
📚 Documentation preview 📚: https://meltano-sdk--2664.org.readthedocs.build/en/2664/
> packaging: Added a constraint on setuptools <= 70.3.0 to fix incompatibility with some dependencies

- singer_sdk/streams/core.py
- singer_sdk/target_base.py
- tests/core/test_mapper.py
- tests/snapshots/mapped_stream/aliased_stream_batch.jsonl
Adds support for `BATCH` messages with `__alias__` using stream maps - a small step towards #1117.
----
📚 Documentation preview 📚: https://meltano-sdk--2667.org.readthedocs.build/en/2667/
> feat: Support stream aliasing of `BATCH` messages via stream maps

- docs/stream_maps.md
- singer_sdk/mapper.py
- tests/core/test_mapper.py
- tests/snapshots/mapped_stream/fake_email_seed_class.jsonl
- tests/snapshots/mapped_stream/fake_email_seed_instance.jsonl
Related:
- Closes #2669
- https://github.com/meltano/sdk/pull/2598#issuecomment-2351878064
----
📚 Documentation preview 📚: https://meltano-sdk--2670.org.readthedocs.build/en/2670/
> refactor: Deprecated `Faker` class in stream maps

- singer_sdk/typing.py
----
📚 Documentation preview 📚: https://meltano-sdk--2676.org.readthedocs.build/en/2676/
> chore: Fix the `warnings.deprecated` import in Python 3.13

- samples/sample_tap_dummy_json/tap_dummyjson/auth.py
https://dummyjson.com/docs/auth
----
📚 Documentation preview 📚: https://meltano-sdk--2684.org.readthedocs.build/en/2684/
> chore: Use a single session to handle authentication steps in DummyJSON

- singer_sdk/helpers/_flattening.py
- tests/core/test_flattening.py
See https://github.com/MeltanoLabs/tap-stackexchange/issues/41
----
📚 Documentation preview 📚: https://meltano-sdk--2683.org.readthedocs.build/en/2683/
> fix: A clear error message is now emitted when flattening is enable but `flattening_max_depth` is not set

- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/test.yml
- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/tox.ini
- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/{{cookiecutter.library_name}}/mapper.py
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/test.yml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/tox.ini
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/graphql-client.py
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/other-client.py
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/rest-client.py
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/sql-client.py
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/streams.py
- cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/test.yml
- cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
- cookiecutter/target-template/{{cookiecutter.target_id}}/tox.ini
- samples/sample_tap_dummy_json/pyproject.toml
Python 3.8 will reach EOL in about one month, so arguably there's no need for new plugins to support it.
- https://devguide.python.org/versions/
- https://endoflife.date/python
----
📚 Documentation preview 📚: https://meltano-sdk--2661.org.readthedocs.build/en/2661/
> refactor(templates): Drop support for Python 3.8 in templates

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
----
📚 Documentation preview 📚: https://meltano-sdk--2694.org.readthedocs.build/en/2694/
> packaging(templates): Remove unused backport `importlib_resources` dependency in tap template

- singer_sdk/streams/rest.py
Closes #2643 
----
📚 Documentation preview 📚: https://meltano-sdk--2697.org.readthedocs.build/en/2697/
> fix: All HTTP timeout exceptions are now retried in REST and GraphQL streams

- docs/stream_maps.md
- singer_sdk/mapper.py
- tests/core/test_mapper.py
- tests/snapshots/mapped_stream/aliased_stream_not_expr.jsonl
- tests/snapshots/mapped_stream/aliased_stream_quoted.jsonl
- tests/snapshots/mapped_stream/builtin_variable_stream_name_alias.jsonl
- tests/snapshots/mapped_stream/builtin_variable_stream_name_alias_expr.jsonl
Allow users to reference the stream name in stream maps __alias__ fields, under a special key:
```
{
"stream_maps": {
"*": {
"__alias__": "'raw_' + __stream_name__"
},
}
```
* Closes #2700 
* Similar to #2283 but `__alias__` was not an evaluated field before now
----
📚 Documentation preview 📚: https://meltano-sdk--2701.org.readthedocs.build/en/2701/
> feat(mappers): Stream name can now be accessed in `__alias__` context of stream maps

- docs/implementation/cli.md
- docs/stream_maps.md
----
📚 Documentation preview 📚: https://meltano-sdk--2705.org.readthedocs.build/en/2705/
> chore: Clean up TODOs in docs

- .github/workflows/api-changes.yml
- .github/workflows/constraints.txt
- .github/workflows/cookiecutter-e2e.yml
- .github/workflows/test.yml
- docs/CONTRIBUTING.md
- noxfile.py
----
📚 Documentation preview 📚: https://meltano-sdk--2713.org.readthedocs.build/en/2713/
> chore: Stop using `nox-poetry`

- poetry.lock
- pyproject.toml
----
📚 Documentation preview 📚: https://meltano-sdk--2714.org.readthedocs.build/en/2714/
> packaging: Remove constraint on `urllib3`

- docs/cli_commands.md
- samples/sample_tap_dummy_json/README.md
----
📚 Documentation preview 📚: https://meltano-sdk--2717.org.readthedocs.build/en/2717/
> docs: Update Meltano commands in examples

- singer_sdk/helpers/_typing.py
- tests/core/test_typing.py
Long due.
----
📚 Documentation preview 📚: https://meltano-sdk--2723.org.readthedocs.build/en/2723/
> fix: JSON schema union types are no longer conformed into boolean values

- noxfile.py
- poetry.lock
- pyproject.toml
- tests/contrib/test_batch_encoder_parquet.py
- tests/samples/test_target_parquet.py
- tests/samples/test_target_sqlite.py
----
📚 Documentation preview 📚: https://meltano-sdk--2734.org.readthedocs.build/en/2734/
> test: Test `parquet` extra on Python 3.13

- poetry.lock
- pyproject.toml
simpleeval 1.0.1 added `pip` as a runtime dependency. It doesn't seem to be tied to any functionality, but it can be problematic so I'm gonna skip it.
Related:
- https://github.com/danthedeckie/simpleeval/issues/155
----
📚 Documentation preview 📚: https://meltano-sdk--2736.org.readthedocs.build/en/2736/
> packaging: Skip `simpleeval` 1.0.1

- pyproject.toml
- singer_sdk/helpers/_compat.py
- singer_sdk/plugin_base.py
- singer_sdk/streams/core.py
- singer_sdk/tap_base.py
----
📚 Documentation preview 📚: https://meltano-sdk--2743.org.readthedocs.build/en/2743/
> refactor: Deprecate passing file paths to plugin and stream initialization

- docs/release_process.md
----
📚 Documentation preview 📚: https://meltano-sdk--2745.org.readthedocs.build/en/2745/
> docs: Document the current release process

- .github/workflows/test.yml
- noxfile.py
- poetry.lock
- pyproject.toml
- samples/aapl/aapl.py
- samples/sample_tap_countries/countries_streams.py
- samples/sample_tap_gitlab/gitlab_graphql_streams.py
- samples/sample_tap_gitlab/gitlab_rest_streams.py
- singer_sdk/_singerlib/catalog.py
- singer_sdk/about.py
- singer_sdk/connectors/sql.py
- singer_sdk/contrib/batch_encoder_jsonl.py
- singer_sdk/helpers/_compat.py
- singer_sdk/helpers/types.py
- singer_sdk/mapper.py
- singer_sdk/sinks/core.py
- singer_sdk/testing/tap_tests.py
- tests/core/configuration/test_dict_config.py
- tests/core/test_connector_sql.py
- tests/samples/test_target_csv.py
----
📚 Documentation preview 📚: https://meltano-sdk--2751.org.readthedocs.build/en/2751/
> refactor: Dropped support for Python 3.8

- singer_sdk/testing/templates.py
----
📚 Documentation preview 📚: https://meltano-sdk--2752.org.readthedocs.build/en/2752/
> chore: Use `importlib.resources` from the standard library

- singer_sdk/helpers/_state.py
- singer_sdk/helpers/_typing.py
- tests/core/test_state_handling.py
This change will return a stringified value for an instance of uuid.UUID.
----
📚 Documentation preview 📚: https://meltano-sdk--2755.org.readthedocs.build/en/2755/
> fix: Safely compare UUID replication keys with state bookmarks

- .github/ISSUE_TEMPLATE/bug.yml
- CHANGELOG.md
- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
- docs/conf.py
- pyproject.toml
- **chore: Final v0.42.0 (#2750)**
- **fix: Safely compare UUID replication keys with state bookmarks (#2756)**
- **chore: Use the branch checked out in the version bump workflow**
- **chore: Release v0.42.1 (#2759)**
----
📚 Documentation preview 📚: https://meltano-sdk--2760.org.readthedocs.build/en/2760/
> chore: Update `main` from `v0.42`

- .github/dependabot.yml
- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/dependabot.yml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/dependabot.yml
- cookiecutter/target-template/{{cookiecutter.target_id}}/.github/dependabot.yml
- poetry.lock
----
📚 Documentation preview 📚: https://meltano-sdk--2769.org.readthedocs.build/en/2769/
> feat(templates): Add `versioning-strategy` to dependabot config of Cookiecutter templates

- singer_sdk/streams/core.py
----
📚 Documentation preview 📚: https://meltano-sdk--2775.org.readthedocs.build/en/2775/
> feat: Log a stream's bookmark (if it's avaiable) when its sync starts

- singer_sdk/plugin_base.py
- tests/core/conftest.py
- tests/core/test_tap_class.py
----
📚 Documentation preview 📚: https://meltano-sdk--2778.org.readthedocs.build/en/2778/
> fix: The path of the offending field is now printed for config validation errors

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/graphql-client.py
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/rest-client.py
- singer_sdk/streams/rest.py
- tests/core/test_streams.py
This means under normal circumstances, `decimal.Decimal` would be used across the board:
1. A float value of `"value": 3.14` in the API response is parsed as `Decimal("3.14")`
2. The `Decimal("3.14")` value is serialized to JSON as `value: 3.14` in the tap output
3. The float value of `"value": 3.14` in the `RECORD` Singer message will be parsed as `Decimal("3.14")` by the target.
That should ensure we preserve precision through the pipeline.
> [!CAUTION]
> Now, this _could_ be a breaking change if folks are doing floating-point math with these values, but I think it's rare enough that we can make do with a call-out in the release notes.
----
📚 Documentation preview 📚: https://meltano-sdk--2780.org.readthedocs.build/en/2780/
> feat(taps): Numeric values are now parsed as `decimal.Decimal` in REST and GraphQL stream responses

- singer_sdk/contrib/filesystem/tap.py
- singer_sdk/testing/templates.py
- tests/samples/test_tap_csv.py
----
📚 Documentation preview 📚: https://meltano-sdk--2785.org.readthedocs.build/en/2785/
> fix: Use FS-specific `listdir` in folder tap

- .pre-commit-config.yaml
- samples/sample_tap_gitlab/gitlab_rest_streams.py
- singer_sdk/connectors/sql.py
- singer_sdk/helpers/_state.py
- singer_sdk/helpers/_typing.py
- singer_sdk/plugin_base.py
- singer_sdk/tap_base.py
- singer_sdk/testing/legacy.py
- singer_sdk/testing/runners.py
- singer_sdk/testing/tap_tests.py
- singer_sdk/typing.py
- tests/samples/test_tap_sqlite.py
----
📚 Documentation preview 📚: https://meltano-sdk--2787.org.readthedocs.build/en/2787/
> chore: Bump Ruff to 0.8.1 and apply `TC006` (`runtime-cast-value`)

- singer_sdk/tap_base.py
Related:
- #2743 
- https://github.com/meltano/sdk/issues/199
- #1409 
----
📚 Documentation preview 📚: https://meltano-sdk--2788.org.readthedocs.build/en/2788/
> refactor: Fail early if input files to `--catalog` or `--state` do not exist

- singer_sdk/contrib/filesystem/tap.py
- singer_sdk/plugin_base.py
- singer_sdk/tap_base.py
- tests/core/test_plugin_base.py
----
📚 Documentation preview 📚: https://meltano-sdk--2790.org.readthedocs.build/en/2790/
> fix: Ensure the required global folder tap settings are merged into the concrete implementation settings

- .github/workflows/codspeed.yml
- tests/core/test_connector_sql.py
Related:
- https://github.com/meltano/sdk/pull/2793
----
📚 Documentation preview 📚: https://meltano-sdk--2794.org.readthedocs.build/en/2794/
> test: Add benchmark for SQL tap discovery

- singer_sdk/connectors/sql.py
- singer_sdk/tap_base.py
- tests/core/test_connector_sql.py
Related:
* https://github.com/MeltanoLabs/tap-postgres/issues/437
* https://github.com/meltano/sdk/issues/1234
----
📚 Documentation preview 📚: https://meltano-sdk--2482.org.readthedocs.build/en/2482/
> feat(taps): Allow SQL tap developers to auto-skip certain schemas from discovery

- samples/sample_tap_bigquery/__init__.py
- singer_sdk/connectors/sql.py
TODO:
----
📚 Documentation preview 📚: https://meltano-sdk--2793.org.readthedocs.build/en/2793/
> perf(taps): Improved discovery performance for SQL taps

- docs/stream_maps.md
----
📚 Documentation preview 📚: https://meltano-sdk--2796.org.readthedocs.build/en/2796/
> docs: Document how to configure nested stream maps values with environment variables in Meltano

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- docs/guides/sql-tap.md
Related:
- #1667 
----
📚 Documentation preview 📚: https://meltano-sdk--2797.org.readthedocs.build/en/2797/
> packaging: SQL taps now require SQLAlchemy 2.0+

- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/graphql-client.py
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/rest-client.py
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/sql-client.py
- cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml
- cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
- samples/sample_tap_dummy_json/.pre-commit-config.yaml
- samples/sample_tap_dummy_json/tox.ini
----
📚 Documentation preview 📚: https://meltano-sdk--2798.org.readthedocs.build/en/2798/
> chore: Update template dependencies

- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
- cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml
- singer_sdk/helpers/capabilities.py
- singer_sdk/sinks/core.py
- tests/samples/test_target_sqlite.py
----
📚 Documentation preview 📚: https://meltano-sdk--2805.org.readthedocs.build/en/2805/
> refactor: Rename setting `activate_version` to `process_activate_version_messages`

- poetry.lock
- pyproject.toml
----
📚 Documentation preview 📚: https://meltano-sdk--2821.org.readthedocs.build/en/2821/
> packaging: Require urllib3 < 2 on Python < 3.10

- singer_sdk/typing.py
- tests/core/test_jsonschema_helpers.py
Closes #2116
----
📚 Documentation preview 📚: https://meltano-sdk--2830.org.readthedocs.build/en/2830/
> feat: Allow developers to mark stream schema and settings fields as deprecated

- pyproject.toml
- uv.lock
This reverts commit 7529cbf78db74f06c61223d9bfde2c74bbfc2c4a.
Causing issues for Poetry-managed downstream packages: https://github.com/meltano/sdk/actions/runs/13075031342/job/36484997547?pr=2857
> revert: Add back some upper Python version constraints in dependencies

- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
----
📚 Documentation preview 📚: https://meltano-sdk--3113.org.readthedocs.build/en/3113/
> fix(templates): Remove redundant `tool.ruff.target-version` from tap template

- singer_sdk/plugin_base.py
Backport of https://github.com/meltano/sdk/pull/3127.
----
📚 Documentation preview 📚: https://meltano-sdk--3135.org.readthedocs.build/en/3135/
> fix: Ensure Singer SDK warnings are logged

- singer_sdk/testing/factory.py
- singer_sdk/testing/suites.py
----
📚 Documentation preview 📚: https://meltano-sdk--3164.org.readthedocs.build/en/3164/
> refactor: Rename `TestSuite` → `SingerTestSuite` to prevent a pytest test collection warning

- cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
- cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
- cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
Python 3.9 reaches EOL in a little over a month.
> feat(templates): Dropped support for Python 3.9 in tap, target and mapper templates
