meltano/sdk

singer_sdk/plugin_base.py

fix: Remove trailing parenthesis from logged version

---

singer_sdk/typing.py
tests/core/test_capabilities.py

fix: Allow lists and dictionaries as types for default JSON values

---

pyproject.toml

docs: Fix PyPI trove classifiers

---

pyproject.toml

Copies from https://github.com/meltano/meltano/pull/6424

ci: Customize commitizen changelog output

---

cookiecutter/target-template/{{cookiecutter.target_id}}/{{cookiecutter.library_name}}/sinks.py
cookiecutter/target-template/{{cookiecutter.target_id}}/{{cookiecutter.library_name}}/target.py

- Create connector class
- Sink inherits from `SQLSink`
- Sink declares `connector_class` attribute
- Target class inherits from `SQLTarget`
- Target declares `sqlalchemy_url` setting.
Closes #815

fix(templates): Generate correct SQL target project from cookiecutter

---

.github/workflows/dependency-review.yml

ci: Use `fossa-cli` to check dependency licenses in CI

---

singer_sdk/streams/core.py

Closes https://github.com/meltano/sdk/issues/874

fix: Change to use json dumps for outputting metrics

---

singer_sdk/sinks/sql.py
tests/core/test_sqlite.py

refactor(targets): Allow overriding the bulk insert statement in `SQLSink`

---

docs/implementation/at_least_once.md
poetry.lock

Check with `nox -rs docs-serve`

docs: Bump Pygments and update dbt example

---

singer_sdk/streams/core.py
singer_sdk/streams/graphql.py
singer_sdk/streams/sql.py

style: Use PEP 563 and 585 in `singer_sdk.streams`

---

singer_sdk/helpers/_singer.py

style: Use PEP 563 and 585 in `singer_sdk.helpers._singer`

---

.github/workflows/constraints.txt
poetry.lock

Related: https://github.com/meltano/meltano/pull/6692

chore: Update `poetry.lock` to Poetry 1.2 format

---

docs/classes/singer_sdk.authenticators.APIAuthenticatorBase.rst
docs/classes/singer_sdk.exceptions.RecordsWithoutSchemaException.rst
docs/classes/singer_sdk.pagination.BaseAPIPaginator.rst
docs/classes/singer_sdk.pagination.BaseHATEOASPaginator.rst
docs/classes/singer_sdk.pagination.BaseOffsetPaginator.rst
docs/classes/singer_sdk.pagination.BasePageNumberPaginator.rst
docs/classes/singer_sdk.pagination.HeaderLinkPaginator.rst
docs/classes/singer_sdk.pagination.JSONPathPaginator.rst
docs/classes/singer_sdk.pagination.LegacyPaginatedStreamProtocol.rst
docs/classes/singer_sdk.pagination.LegacyStreamPaginator.rst
docs/classes/singer_sdk.pagination.SimpleHeaderPaginator.rst
docs/classes/singer_sdk.pagination.SinglePagePaginator.rst

----
:books: Documentation preview :books:: https://meltano-sdk--950.org.readthedocs.build/en/950/

docs: Document missing initializers for authentication and pagination helpers

---

docs/_static/css/custom.css

----
:books: Documentation preview :books:: https://meltano-sdk--988.org.readthedocs.build/en/988/

docs: Add pipe before SDK logo in header

---

README.md

----
:books: Documentation preview :books:: https://meltano-sdk--1045.org.readthedocs.build/en/1045/

chore: Update marketing lang

---

README.md
cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
cookiecutter/target-template/{{cookiecutter.target_id}}/README.md
cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
docs/conf.py
docs/index.rst
pyproject.toml
singer_sdk/__init__.py
singer_sdk/helpers/_batch.py
singer_sdk/plugin_base.py
singer_sdk/streams/__init__.py
singer_sdk/streams/rest.py

----
:books: Documentation preview :books:: https://meltano-sdk--1053.org.readthedocs.build/en/1053/

chore: Rename to "Meltano Singer SDK"

---

singer_sdk/target_base.py

Fixes #1064
----
:books: Documentation preview :books:: https://meltano-sdk--1192.org.readthedocs.build/en/1192/

fix(taps): Change max record age for emitting state messages to 5 instead of 30 mins

---

.github/workflows/version_bump.yml

----
:books: Documentation preview :books:: https://meltano-sdk--1280.org.readthedocs.build/en/1280/

fix: set repo file perms after checkout in Version bump workflow

---

.github/workflows/version_bump.yml

----
:books: Documentation preview :books:: https://meltano-sdk--1281.org.readthedocs.build/en/1281/

fix: apply Version bump commit file perms with sudo

---

docs/stream_maps.md
poetry.lock

See https://github.com/meltano/meltano/issues/7165#issuecomment-1397531731
----
:books: Documentation preview :books:: https://meltano-sdk--1335.org.readthedocs.build/en/1335/

docs: Stream maps example for adding property with hardcoded string value

---

.github/CODEOWNERS

----
:books: Documentation preview :books:: https://meltano-sdk--1375.org.readthedocs.build/en/1375/

chore: Update `CODEOWNERS`

---

.github/workflows/version_bump.yml

As per [commitizen-action#56](https://github.com/commitizen-tools/commitizen-action/issues/56)
----
:books: Documentation preview :books:: https://meltano-sdk--1392.org.readthedocs.build/en/1392/

ci: update commitizen

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature.yml

----
:books: Documentation preview :books:: https://meltano-sdk--1450.org.readthedocs.build/en/1450/

chore: Update issue forms

---

pyproject.toml
singer_sdk/_singerlib/catalog.py
singer_sdk/_singerlib/messages.py
singer_sdk/_singerlib/schema.py

----
:books: Documentation preview :books:: https://meltano-sdk--1470.org.readthedocs.build/en/1470/

chore: Enable `UP` (pyupgrade) checks with Ruff

---

pyproject.toml
singer_sdk/helpers/_secrets.py
singer_sdk/helpers/_typing.py
singer_sdk/sinks/batch.py
singer_sdk/sinks/core.py
singer_sdk/sinks/record.py
singer_sdk/streams/core.py
singer_sdk/streams/rest.py
singer_sdk/testing/factory.py
tests/core/configuration/test_dict_config.py
tests/core/test_connector_sql.py
tests/core/test_jsonschema_helpers.py
tests/core/test_mapper.py
tests/core/test_plugin_base.py
tests/samples/conftest.py

- `YTT` (flake8-2020)
- `T10` (flake8-debugger)
- `ICN` (flake8-import-conventions)
- `PIE` (flake8-pie)
- `PT`  (flake8-pytest-style)
----
:books: Documentation preview :books:: https://meltano-sdk--1488.org.readthedocs.build/en/1488/

chore: Enable more Ruff rules

---

pyproject.toml
singer_sdk/_singerlib/utils.py
singer_sdk/plugin_base.py
singer_sdk/sinks/sql.py
singer_sdk/typing.py

----
:books: Documentation preview :books:: https://meltano-sdk--1505.org.readthedocs.build/en/1505/

chore: Enable `RSE` Ruff checks

---

docs/conf.py
pyproject.toml
samples/aapl/aapl.py
samples/sample_target_csv/csv_target_sink.py
singer_sdk/testing/runners.py
singer_sdk/testing/templates.py
tests/conftest.py
tests/cookiecutters/test_cookiecutter.py
tests/core/configuration/test_dict_config.py
tests/samples/test_target_csv.py

----
:books: Documentation preview :books:: https://meltano-sdk--1516.org.readthedocs.build/en/1516/

chore: Enable `PTH` Ruff checks

---

pyproject.toml
singer_sdk/authenticators.py
singer_sdk/mapper.py
singer_sdk/sinks/core.py
singer_sdk/testing/tap_tests.py
tests/core/test_mapper.py

----
:books: Documentation preview :books:: https://meltano-sdk--1550.org.readthedocs.build/en/1550/

chore: Enable `BLE` (flake8-blind-except) Ruff checks

---

pyproject.toml
singer_sdk/authenticators.py
singer_sdk/connectors/sql.py
singer_sdk/helpers/_typing.py
singer_sdk/io_base.py
singer_sdk/sinks/core.py
singer_sdk/streams/rest.py
singer_sdk/testing/tap_tests.py
singer_sdk/testing/templates.py
tests/external/test_tap_gitlab.py
tests/external/test_tap_google_analytics.py
tests/samples/test_target_sqlite.py

----
:books: Documentation preview :books:: https://meltano-sdk--1551.org.readthedocs.build/en/1551/

chore: Enable `B` (flake8-bugbear) Ruff checks

---

docs/conf.py
pyproject.toml
samples/sample_tap_gitlab/gitlab_rest_streams.py
samples/sample_target_parquet/parquet_target_sink.py
singer_sdk/_singerlib/messages.py
singer_sdk/_singerlib/schema.py
singer_sdk/cli/common_options.py
singer_sdk/helpers/_batch.py
singer_sdk/helpers/jsonpath.py
singer_sdk/mapper.py
singer_sdk/mapper_base.py
singer_sdk/plugin_base.py
singer_sdk/tap_base.py
singer_sdk/target_base.py
singer_sdk/testing/legacy.py
singer_sdk/testing/runners.py
singer_sdk/testing/tap_tests.py
singer_sdk/testing/target_tests.py
singer_sdk/testing/templates.py
singer_sdk/typing.py

----
:books: Documentation preview :books:: https://meltano-sdk--1552.org.readthedocs.build/en/1552/

chore: Enable `A` (flake8-builtins) Ruff checks

---

docs/conf.py

----
:books: Documentation preview :books:: https://meltano-sdk--1553.org.readthedocs.build/en/1553/

docs: Change link color from pink to blue

---

pyproject.toml
samples/sample_tap_google_analytics/ga_tap_stream.py
singer_sdk/connectors/sql.py
singer_sdk/helpers/_catalog.py
singer_sdk/helpers/_flattening.py
singer_sdk/helpers/_typing.py
singer_sdk/streams/rest.py
singer_sdk/testing/runners.py
tests/core/test_capabilities.py
tests/core/test_connector_sql.py

----
:books: Documentation preview :books:: https://meltano-sdk--1566.org.readthedocs.build/en/1566/

chore: Enable `RUF` Ruff checks

---

docs/testing.md

I noticed a few typos while going through the testing guide.
----
:books: Documentation preview :books:: https://meltano-sdk--1595.org.readthedocs.build/en/1595/

chore: Update testing.md

---

.github/CODEOWNERS

----
:books: Documentation preview :books:: https://meltano-sdk--1618.org.readthedocs.build/en/1618/

chore: Update GitHub `CODEOWNERS`

---

.github/workflows/release.yml

----
:books: Documentation preview :books:: https://meltano-sdk--1635.org.readthedocs.build/en/1635/

chore: Use PyPI trusted publisher

---

.github/workflows/version_bump.yml

----
:books: Documentation preview :books:: https://meltano-sdk--1636.org.readthedocs.build/en/1636/

ci: Fix file permissions to create PR in version bump workflow

---

.pre-commit-config.yaml
pyproject.toml
samples/sample_tap_gitlab/gitlab_rest_streams.py
singer_sdk/_singerlib/messages.py
singer_sdk/authenticators.py
singer_sdk/configuration/_dict_config.py
singer_sdk/connectors/sql.py
singer_sdk/helpers/_catalog.py
singer_sdk/helpers/_flattening.py
singer_sdk/helpers/_state.py
singer_sdk/helpers/_typing.py
singer_sdk/helpers/_util.py
singer_sdk/io_base.py
singer_sdk/mapper.py
singer_sdk/mapper_base.py
singer_sdk/pagination.py
singer_sdk/plugin_base.py
singer_sdk/sinks/core.py
singer_sdk/sinks/sql.py
singer_sdk/streams/core.py
singer_sdk/streams/graphql.py
singer_sdk/streams/sql.py
singer_sdk/tap_base.py
singer_sdk/target_base.py
singer_sdk/testing/tap_tests.py
singer_sdk/testing/templates.py
singer_sdk/typing.py
tests/core/rest/test_backoff.py
tests/samples/test_target_sqlite.py

----
:books: Documentation preview :books:: https://meltano-sdk--1658.org.readthedocs.build/en/1658/

chore: Enable `EM` (flake8-error-message) Ruff checks

---

pyproject.toml

No fixes required! :)
----
:books: Documentation preview :books:: https://meltano-sdk--1696.org.readthedocs.build/en/1696/

chore: Enable `Q` (flake8-quotes) Ruff checks

---

pyproject.toml
singer_sdk/_singerlib/catalog.py
singer_sdk/helpers/_flattening.py
singer_sdk/helpers/_typing.py
singer_sdk/mapper.py
singer_sdk/streams/core.py
singer_sdk/testing/factory.py
singer_sdk/testing/legacy.py
singer_sdk/typing.py

----
:books: Documentation preview :books:: https://meltano-sdk--1697.org.readthedocs.build/en/1697/

chore: Enable `C90` (mccabe) Ruff checks

---

cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml
cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
noxfile.py

----
:books: Documentation preview :books:: https://meltano-sdk--1722.org.readthedocs.build/en/1722/

chore(templates): Bump `requests` and pre-commit dependencies in templates

---

cookiecutter/target-template/{{cookiecutter.target_id}}/README.md

----
:books: Documentation preview :books:: https://meltano-sdk--1742.org.readthedocs.build/en/1742/

fix(templates): Recommend `meltano run` in target cookiecutter README 

---

.github/ISSUE_TEMPLATE/feature.yml

----
:books: Documentation preview :books:: https://meltano-sdk--1716.org.readthedocs.build/en/1716/

chore: Add `Cookiecutter templates` to "feature" issue template

---

.github/ISSUE_TEMPLATE/feature.yml

----
:books: Documentation preview :books:: https://meltano-sdk--1764.org.readthedocs.build/en/1764/

chore: add tests to issue template options

---

singer_sdk/helpers/capabilities.py

----
:books: Documentation preview :books:: https://meltano-sdk--1771.org.readthedocs.build/en/1771/

fix: Add descriptions for `batch_config` properties

---

singer_sdk/batch.py

Closes #1014
----
:books: Documentation preview :books:: https://meltano-sdk--1796.org.readthedocs.build/en/1796/

fix: Create batch directory if missing

---

singer_sdk/batch.py
tests/core/test_batch.py

Closes #1825
----
:books: Documentation preview :books:: https://meltano-sdk--1826.org.readthedocs.build/en/1826/

fix: Serialization of `decimal.Decimal`

---

.pre-commit-config.yaml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml

----
:books: Documentation preview :books:: https://meltano-sdk--1845.org.readthedocs.build/en/1845/

chore: Use `--show-fixes` Ruff flag

---

.github/stale.yml

----
:books: Documentation preview :books:: https://meltano-sdk--1846.org.readthedocs.build/en/1846/

chore: Add stale bot config

---

.github/ISSUE_TEMPLATE/bug.yml
.github/workflows/test.yml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/{% if cookiecutter.include_ci_files == 'GitHub' %}test.yml{%endif%}
cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/tox.ini
cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/{%if 'REST' == cookiecutter.stream_type %}client.py{%endif%}
cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/{% if cookiecutter.include_ci_files == 'GitHub' %}test.yml{%endif%}
cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
cookiecutter/target-template/{{cookiecutter.target_id}}/tox.ini
noxfile.py
poetry.lock
pyproject.toml
singer_sdk/connectors/sql.py
singer_sdk/helpers/_batch.py
singer_sdk/helpers/_compat.py
singer_sdk/helpers/_flattening.py
singer_sdk/helpers/_secrets.py
singer_sdk/helpers/_state.py
singer_sdk/helpers/_typing.py
singer_sdk/pagination.py
singer_sdk/streams/sql.py

Closes https://github.com/meltano/sdk/issues/1659
----
:books: Documentation preview :books:: https://meltano-sdk--1837.org.readthedocs.build/en/1837/

fix!: Drop support for Python 3.7

---

singer_sdk/plugin_base.py
singer_sdk/sinks/core.py
singer_sdk/sinks/sql.py
tests/core/sinks/test_sdc_metadata.py

----
:books: Documentation preview :books:: https://meltano-sdk--1878.org.readthedocs.build/en/1878/

feat: Add `_sdc_sync_started_at` metadata column to indicate the start of the target process

---

singer_sdk/target_base.py
tests/conftest.py
tests/core/test_target_base.py

Closes #1879 
----
:books: Documentation preview :books:: https://meltano-sdk--1880.org.readthedocs.build/en/1880/

fix: Append batch config if target supports the batch capability

---

cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
pyproject.toml

----
:books: Documentation preview :books:: https://meltano-sdk--1900.org.readthedocs.build/en/1900/

chore: Bump SDK version in mapper template

---

singer_sdk/helpers/_state.py

----
:books: Documentation preview :books:: https://meltano-sdk--1917.org.readthedocs.build/en/1917/

chore: Make Ruff happy

---

pyproject.toml
singer_sdk/tap_base.py
singer_sdk/testing/tap_tests.py
singer_sdk/typing.py

----
:books: Documentation preview :books:: https://meltano-sdk--1926.org.readthedocs.build/en/1926/

chore: Enable Ruff's PERF checks and apply minor refactorings

---

docs/conf.py

----
:books: Documentation preview :books:: https://meltano-sdk--1932.org.readthedocs.build/en/1932/

chore: Remove banner

---

.github/workflows/version_bump.yml
pyproject.toml

----
:books: Documentation preview :books:: https://meltano-sdk--1958.org.readthedocs.build/en/1958/

chore: Use Melty token to create version bump PR

---

docs/conf.py
poetry.lock
pyproject.toml

Closes https://github.com/meltano/sdk/issues/2038
----
:books: Documentation preview :books:: https://meltano-sdk--2039.org.readthedocs.build/en/2039/

docs: Add 404 page with `sphinx-notfound-page`

---

pyproject.toml
singer_sdk/about.py
singer_sdk/connectors/sql.py
singer_sdk/helpers/_state.py
singer_sdk/streams/sql.py

----
:books: Documentation preview :books:: https://meltano-sdk--2077.org.readthedocs.build/en/2077/

chore: Remove some redundant calls to `typing.cast`

---

tests/core/rest/test_authenticators.py

----
:books: Documentation preview :books:: https://meltano-sdk--2089.org.readthedocs.build/en/2089/

test: Test auth token expiration

---

.github/workflows/version_bump.yml

----
:books: Documentation preview :books:: https://meltano-sdk--2091.org.readthedocs.build/en/2091/

chore: Auto-toggle publishing discussions for releases

---

tests/core/test_io.py

This PR adds benchmarks for the JSON encoding and decoding done by `SingerWriter.format_message` and `SingerReader.deserialize_json`

test: Benchmarks for JSON encoding and decoding

---

poetry.lock
pyproject.toml
singer_sdk/streams/core.py
tests/core/conftest.py
tests/core/test_streams.py

fix(taps): Respect forced replication method when retrieving state

---

singer_sdk/streams/rest.py

----
📚 Documentation preview 📚: https://meltano-sdk--2111.org.readthedocs.build/en/2111/

docs: Fix broken requests documentation links

---

noxfile.py
singer_sdk/_singerlib/catalog.py
singer_sdk/_singerlib/messages.py
singer_sdk/connectors/sql.py
singer_sdk/mapper.py
singer_sdk/sinks/core.py
singer_sdk/sinks/sql.py
singer_sdk/streams/core.py
singer_sdk/streams/sql.py
singer_sdk/tap_base.py
singer_sdk/target_base.py

----
📚 Documentation preview 📚: https://meltano-sdk--2122.org.readthedocs.build/en/2122/

chore: Use `typing.Sequence` in methods that should accept covariant types

---

pyproject.toml
singer_sdk/connectors/sql.py
singer_sdk/sinks/sql.py
singer_sdk/streams/sql.py
singer_sdk/typing.py
tests/conftest.py
tests/core/test_connector_sql.py
tests/core/test_sql_typing.py
tests/core/test_typing.py
tests/samples/conftest.py
tests/samples/test_target_sqlite.py

----
📚 Documentation preview 📚: https://meltano-sdk--2123.org.readthedocs.build/en/2123/

chore: Enforce importing `import sqlalchemy as sa`

---

.github/dependabot.yml
.github/workflows/codeql-analysis.yml
.github/workflows/codspeed.yml
.github/workflows/cookiecutter-e2e.yml
.github/workflows/dependency-review.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/version_bump.yml
noxfile.py

----
📚 Documentation preview 📚: https://meltano-sdk--2133.org.readthedocs.build/en/2133/

ci: Group GitHub Action dependabot updates

---

cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/rest-client.py
cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/streams.py
poetry.lock
pyproject.toml
samples/aapl/aapl.py
samples/sample_tap_countries/countries_streams.py
samples/sample_tap_gitlab/gitlab_graphql_streams.py
samples/sample_tap_gitlab/gitlab_rest_streams.py
samples/sample_tap_google_analytics/ga_tap_stream.py
singer_sdk/helpers/_compat.py
singer_sdk/streams/core.py
singer_sdk/testing/runners.py
singer_sdk/testing/templates.py
tests/samples/test_target_csv.py

----
📚 Documentation preview 📚: https://meltano-sdk--2130.org.readthedocs.build/en/2130/

refactor: Allow loading stream schemas from `importlib.resources.abc.Traversable` types

---

cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/{% if cookiecutter.include_ci_files == 'GitHub' %}test.yml{%endif%}
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/tox.ini
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/test.yml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/tox.ini
cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/rest-client.py
cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/test.yml
cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml
cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
cookiecutter/target-template/{{cookiecutter.target_id}}/tox.ini

----
📚 Documentation preview 📚: https://meltano-sdk--2139.org.readthedocs.build/en/2139/

chore(templates): Bump cookiecutter dependencies

---

.github/workflows/codspeed.yml

----
📚 Documentation preview 📚: https://meltano-sdk--2141.org.readthedocs.build/en/2141/

ci: Trigger codspeed benchmarks only on relevant file changes

---

noxfile.py
poetry.lock
pyproject.toml
tests/core/test_connector_sql.py

----
📚 Documentation preview 📚: https://meltano-sdk--2145.org.readthedocs.build/en/2145/

chore: Bump `duckdb` test dependency

---

docs/parent_streams.md
singer_sdk/streams/core.py
tests/core/test_parent_child.py

Closes #1862 
----
📚 Documentation preview 📚: https://meltano-sdk--2144.org.readthedocs.build/en/2144/

feat: Support fanning out parent record into multiple child contexts/syncs

---

.github/workflows/test.yml
pyproject.toml

----
📚 Documentation preview 📚: https://meltano-sdk--2161.org.readthedocs.build/en/2161/

ci: Fix coverage measurement on Windows

---

poetry.lock
pyproject.toml

----
📚 Documentation preview 📚: https://meltano-sdk--2165.org.readthedocs.build/en/2165/

chore: Bump docs dependencies

---

codecov.yml

----
📚 Documentation preview 📚: https://meltano-sdk--2169.org.readthedocs.build/en/2169/

chore: Add `codecov.yml`

---

docs/faq.md
singer_sdk/helpers/_state.py
tests/core/test_state_handling.py

----
📚 Documentation preview 📚: https://meltano-sdk--2168.org.readthedocs.build/en/2168/

docs: Explain `Progress is not resumable if interrupted` in docs FAQ

---

.github/workflows/cookiecutter-e2e.yml
.github/workflows/test.yml
.github/workflows/version_bump.yml
noxfile.py
poetry.lock

----
📚 Documentation preview 📚: https://meltano-sdk--2201.org.readthedocs.build/en/2201/

test: Use Python 3.12 in CI

---

noxfile.py
poetry.lock
pyproject.toml
tests/core/test_connector_sql.py

A release was deleted from PyPI :/
https://github.com/meltano/sdk/pull/2170#issuecomment-1918257656
----
📚 Documentation preview 📚: https://meltano-sdk--2206.org.readthedocs.build/en/2206/

test: Reference a duckdb version with wheels

---

singer_sdk/connectors/sql.py
singer_sdk/typing.py
tests/samples/conftest.py
tests/samples/test_tap_sqlite.py

Closes https://github.com/meltano/sdk/issues/2224
----
📚 Documentation preview 📚: https://meltano-sdk--2225.org.readthedocs.build/en/2225/

fix(taps): Support non-nullable but not required SQL columns

---

tests/core/test_metrics.py

This was previously flaky and slow (always took 1s to complete).
----
📚 Documentation preview 📚: https://meltano-sdk--2282.org.readthedocs.build/en/2282/

test: Made the `test_sync_timer` test faster by using `time_machine`

---

poetry.lock

----
📚 Documentation preview 📚: https://meltano-sdk--2332.org.readthedocs.build/en/2332/

chore(deps-dev): Bump `pytest-codspeed`

---

poetry.lock
pyproject.toml

----
📚 Documentation preview 📚: https://meltano-sdk--2368.org.readthedocs.build/en/2368/

chore: Ensure `PyJWT` and `cryptography` are always installed for now

---

poetry.lock

----
📚 Documentation preview 📚: https://meltano-sdk--2373.org.readthedocs.build/en/2373/

chore: Run `poetry lock`

---

cookiecutter/tap-template/{{cookiecutter.tap_id}}/meltano.yml
cookiecutter/target-template/{{cookiecutter.target_id}}/meltano.yml

----
📚 Documentation preview 📚: https://meltano-sdk--2375.org.readthedocs.build/en/2375/

fix(templates): Added `sensitive: true` to password settings in templates

---

.github/workflows/test.yml

Related:
* https://github.com/actions/setup-python/issues/808
----
📚 Documentation preview 📚: https://meltano-sdk--2390.org.readthedocs.build/en/2390/

ci: Fix macOS workflows

---

singer_sdk/streams/core.py
singer_sdk/streams/graphql.py
singer_sdk/streams/rest.py
singer_sdk/streams/sql.py

Closes #2096
----
📚 Documentation preview 📚: https://meltano-sdk--2415.org.readthedocs.build/en/2415/

chore: Standardized `record` and `context` types

---

.github/workflows/test.yml
noxfile.py
poetry.lock
pyproject.toml

----
📚 Documentation preview 📚: https://meltano-sdk--2416.org.readthedocs.build/en/2416/

chore: Check dependency issues with `deptry`

---

cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml

----
📚 Documentation preview 📚: https://meltano-sdk--2430.org.readthedocs.build/en/2430/

chore(templates): Bump cookiecutter pre-commit hooks

---

samples/sample_tap_gitlab/schemas/projects.json

----
📚 Documentation preview 📚: https://meltano-sdk--2434.org.readthedocs.build/en/2434/

test: Drop missing tap-gitlab project fields in integration test

---

docs/parent_streams.md

----
📚 Documentation preview 📚: https://meltano-sdk--2436.org.readthedocs.build/en/2436/

docs: Documented how context fields are passed to a child stream

---

cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml

----
📚 Documentation preview 📚: https://meltano-sdk--2437.org.readthedocs.build/en/2437/

chore(templates): Bump `importlib-resources` in tap template

---

singer_sdk/helpers/_state.py
tests/core/test_state_handling.py

Related:
* Closes #1714
----
📚 Documentation preview 📚: https://meltano-sdk--2438.org.readthedocs.build/en/2438/

fix: Null replication values are now handled when incrementing bookmarks

---

pyproject.toml

----
📚 Documentation preview 📚: https://meltano-sdk--2439.org.readthedocs.build/en/2439/

chore: Bump build backend `poetry-dynamic-versioning` to 1.3.0

---

.github/workflows/release.yml

----
📚 Documentation preview 📚: https://meltano-sdk--2447.org.readthedocs.build/en/2447/

chore: Attest build artifacts

---

singer_sdk/authenticators.py
singer_sdk/helpers/_util.py

----
📚 Documentation preview 📚: https://meltano-sdk--2453.org.readthedocs.build/en/2453/

refactor: Change to return type of `utc_now` from `pendulum.DateTime` to `datetime.datetime`

---

.pre-commit-config.yaml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml

----
📚 Documentation preview 📚: https://meltano-sdk--2480.org.readthedocs.build/en/2480/

chore: Update all pre-commit hooks

---

docs/stream_maps.md

----
📚 Documentation preview 📚: https://meltano-sdk--2506.org.readthedocs.build/en/2506/

docs: Fixed a typo in the stream maps docs

---

cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/build.yml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/build.yml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/build.yml
cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml

----
📚 Documentation preview 📚: https://meltano-sdk--2512.org.readthedocs.build/en/2512/

chore: Bumped template dependencies

---

.github/workflows/api-changes.yml
.github/workflows/constraints.txt
noxfile.py

Closes https://github.com/meltano/sdk/issues/1565
----
📚 Documentation preview 📚: https://meltano-sdk--2538.org.readthedocs.build/en/2538/

chore: Use `griffe` to catch breaking API changes

---

.github/semantic.yml

x-ref: https://github.com/meltano/commitizen-version-bump/pull/78
----
📚 Documentation preview 📚: https://meltano-sdk--2547.org.readthedocs.build/en/2547/

chore: Add a `packaging` PR category

---

docs/partitioning.md

----
📚 Documentation preview 📚: https://meltano-sdk--2556.org.readthedocs.build/en/2556/

docs: Reference state partitioning in stream partitioning page

---

singer_sdk/_singerlib/encoding/__init__.py
singer_sdk/_singerlib/encoding/_simple.py
singer_sdk/_singerlib/messages.py
singer_sdk/io_base.py

----
📚 Documentation preview 📚: https://meltano-sdk--2565.org.readthedocs.build/en/2565/

chore: Make it easier to switch Singer reader and writer IO implementations in plugin classes

---

docs/CONTRIBUTING.md

----
📚 Documentation preview 📚: https://meltano-sdk--2579.org.readthedocs.build/en/2579/

docs: Documented support for `packaging` semantic type in contributing guide

---

cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml
noxfile.py

----
📚 Documentation preview 📚: https://meltano-sdk--2587.org.readthedocs.build/en/2587/

chore: Update pre-commit hooks in cookiecutters

---

.github/ISSUE_TEMPLATE/bug.yml

----
📚 Documentation preview 📚: https://meltano-sdk--2615.org.readthedocs.build/en/2615/

chore: Update bug issue template

---

pyproject.toml
singer_sdk/_singerlib/encoding/_simple.py
singer_sdk/authenticators.py
singer_sdk/connectors/sql.py
singer_sdk/helpers/_batch.py
singer_sdk/helpers/_catalog.py
singer_sdk/helpers/_state.py
singer_sdk/mapper.py
singer_sdk/plugin_base.py
singer_sdk/streams/core.py
singer_sdk/streams/graphql.py
singer_sdk/tap_base.py
singer_sdk/testing/legacy.py
singer_sdk/testing/tap_tests.py
singer_sdk/typing.py

Applied `pipx run 'sp-repo-review[cli]' .` to this project.
----
📚 Documentation preview 📚: https://meltano-sdk--2645.org.readthedocs.build/en/2645/

chore: Apply repo-review to this project

---

.pre-commit-config.yaml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml

----
📚 Documentation preview 📚: https://meltano-sdk--2649.org.readthedocs.build/en/2649/

chore(templates): update pre-commit hooks

---

cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/build.yml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/test.yml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/tox.ini
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/build.yml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/test.yml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/README.md
cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/tox.ini
cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/build.yml
cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/test.yml
cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml
cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
cookiecutter/target-template/{{cookiecutter.target_id}}/tox.ini

----
📚 Documentation preview 📚: https://meltano-sdk--2695.org.readthedocs.build/en/2695/

refactor(templates): Update dependencies in templates

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml

----
📚 Documentation preview 📚: https://meltano-sdk--2707.org.readthedocs.build/en/2707/

feat: Bumped simpleeval to 1.0

---

.github/workflows/test.yml

----
📚 Documentation preview 📚: https://meltano-sdk--2722.org.readthedocs.build/en/2722/

ci: Install dependency prereleases in CI

---

.github/workflows/cookiecutter-e2e.yml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/build.yml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/test.yml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/build.yml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/test.yml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/{{cookiecutter.library_name}}/other-client.py
cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/build.yml
cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/test.yml
cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml

----
📚 Documentation preview 📚: https://meltano-sdk--2742.org.readthedocs.build/en/2742/

feat(templates): Update dependencies in templates

---

.github/workflows/codeql-analysis.yml
.github/workflows/codspeed.yml
.github/workflows/cookiecutter-e2e.yml
.github/workflows/test.yml

----
📚 Documentation preview 📚: https://meltano-sdk--2747.org.readthedocs.build/en/2747/

ci: Run tests on `v*` branches

---

.github/ISSUE_TEMPLATE/bug.yml
.github/workflows/release.yml
.github/workflows/version_bump.yml
.pre-commit-config.yaml
CHANGELOG.md
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/pyproject.toml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/pyproject.toml
cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml
cookiecutter/target-template/{{cookiecutter.target_id}}/pyproject.toml
docs/conf.py
poetry.lock
pyproject.toml

----
📚 Documentation preview 📚: https://meltano-sdk--2750.org.readthedocs.build/en/2750/

chore: Final v0.42.0

---

.github/workflows/version_bump.yml

----
📚 Documentation preview 📚: https://meltano-sdk--2758.org.readthedocs.build/en/2758/

chore: Use the branch checked out in the version bump workflow

---

singer_sdk/_singerlib/encoding/_base.py
tests/core/test_io.py

----
📚 Documentation preview 📚: https://meltano-sdk--2765.org.readthedocs.build/en/2765/

feat(targets): The last received Singer message is now logged when the target fails

---

.readthedocs.yml

----
📚 Documentation preview 📚: https://meltano-sdk--2795.org.readthedocs.build/en/2795/

chore: Use Python 3.13 to build docs

---

singer_sdk/streams/rest.py
tests/core/test_streams.py

Follows from https://github.com/meltano/sdk/pull/2762
----
📚 Documentation preview 📚: https://meltano-sdk--2807.org.readthedocs.build/en/2807/

fix: Allow developers to set `RESTStream.http_method`

---

.pre-commit-config.yaml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.github/workflows/build.yml
cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/.pre-commit-config.yaml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.github/workflows/build.yml
cookiecutter/tap-template/{{cookiecutter.tap_id}}/.pre-commit-config.yaml
cookiecutter/target-template/{{cookiecutter.target_id}}/.github/workflows/build.yml
cookiecutter/target-template/{{cookiecutter.target_id}}/.pre-commit-config.yaml

----
📚 Documentation preview 📚: https://meltano-sdk--2811.org.readthedocs.build/en/2811/

chore: Update template dependencies

---

poetry.lock
pyproject.toml

----
📚 Documentation preview 📚: https://meltano-sdk--2822.org.readthedocs.build/en/2822/

packaging: Make paramiko and transitive SSH dependencies optional

---

cookiecutter/mapper-template/{{cookiecutter.mapper_id}}/README.md
cookiecutter/tap-template/{{cookiecutter.tap_id}}/README.md
cookiecutter/target-template/{{cookiecutter.target_id}}/README.md
docs/python_tips.md
samples/sample_tap_dummy_json/README.md

----
📚 Documentation preview 📚: https://meltano-sdk--2825.org.readthedocs.build/en/2825/

chore: Fix typo PyPi -> PyPI

---

pyproject.toml

----
📚 Documentation preview 📚: https://meltano-sdk--3224.org.readthedocs.build/en/3224/

packaging: Bump hatch-vcs to 0.5.0

---

pyproject.toml
uv.lock

----
📚 Documentation preview 📚: https://meltano-sdk--3225.org.readthedocs.build/en/3225/

chore: Require `mypy` 1.17+
